In [2]:
%pip install sqlalchemy pymysql python-dotenv

Requirement already satisfied: sqlalchemy in /Users/grigo/gits/seminars/gfu/Python_individuell/.venv/lib/python3.12/site-packages (2.0.42)
Requirement already satisfied: pymysql in /Users/grigo/gits/seminars/gfu/Python_individuell/.venv/lib/python3.12/site-packages (1.1.1)
Requirement already satisfied: python-dotenv in /Users/grigo/gits/seminars/gfu/Python_individuell/.venv/lib/python3.12/site-packages (1.1.1)
Requirement already satisfied: typing-extensions>=4.6.0 in /Users/grigo/gits/seminars/gfu/Python_individuell/.venv/lib/python3.12/site-packages (from sqlalchemy) (4.14.1)
Note: you may need to restart the kernel to use updated packages.

In [3]:
import pandas as pd
from sqlalchemy import create_engine
from dotenv import load_dotenv
import os # Betriebssystem-Tools

#load_dotenv()

os.environ["MYSQL_USER"]

# Bitte NIE so: 

# MYSQL_USER = 'dein_user'
# MYSQL_PASS = 'dein_passwort'
# MYSQL_HOST = 'localhost'  # oder echte IP/Domain deines Servers
# MYSQL_PORT = 3306         # Standardport
# MYSQL_DB   = 'deine_datenbank'




#db_url = f"mysql+pymysql://{MYSQL_USER}:{MYSQL_PASS}@{MYSQL_HOST}:{MYSQL_PORT}/{MYSQL_DB}"

os.environ

KeyError: 'MYSQL_USER'

In [11]:
import sqlite3


with sqlite3.connect("personal.db") as con:
    df = pd.read_sql("SELECT * FROM personal", con)
    df2 = pd.read_sql("SELECT Vorname, Nachname, Gehalt_m FROM personal WHERE Gehalt_m > 40000", con)

df
df2

           Vorname     Nachname  Gehalt_m
0             Nils  Ditschlerin     86595
1            Laura       Hornig     77708
2             Ella     Schuster    118794
3        Roselinde       Söding     46124
4          Juliana      Steckel     75834
...            ...          ...       ...
25819    Charlotte     Stiebitz     92091
25820  Franz-Xaver       Reuter     76610
25821       Alexei        Nette     54179
25822      Karolin       Weller     78911
25823       Ildiko         Bähr     47855

[25824 rows x 3 columns]

In [14]:
with sqlite3.connect("personal.db") as con:
    for chunk in pd.read_sql("SELECT * FROM personal",con,chunksize=10000):
        print(chunk.shape)

(10000, 18)
(10000, 18)
(10000, 18)

In [18]:
df

,MitarbeiterID,Dienstnummer,Vorname,Nachname,Geburtsdatum,Geschlecht,Adresse,Telefon,Email,Familienstand,Beruf,Abteilung,Gehalt_m,Vertrag,Letzte Gehaltsverhandlung,Steuerklasse,Urlaubstage,Initialien
0,413885b6-da63-4e89-a887-926f6cc40b9f,NZ8637335,Nils,Ditschlerin,1963-04-06,divers,"Wellerplatz 6461, 49247 Uffenheim",06376 474749,suzannesoeding@example.com,ledig,Elektroniker,IT,86595,befristet,2020-12-16,V,24,ND
1,be400057-3025-422f-be87-d53f96a94451,GR9519484,Laura,Hornig,2002-04-27,männlich,"Adele-Davids-Gasse 55-41, 31945 Garmisch-Parte...",+49(0)0632 28106,yruppersberger@example.org,verheiratet,Florist,HR,77708,unbefristet,2022-08-17,IV,23,LH
2,aa5db6ab-e4f6-44c5-b2e6-ca14a2a4904a,CB2082368,Hellmuth,Ruppert,1967-10-15,divers,"Belinda-Beckmann-Weg 0, 60208 Bautzen",(05529) 024082,dehmelberthold@example.org,verheiratet,Fleischer,IT,33700,unbefristet,2021-06-20,VI,6,HR
3,74ad6f76-82af-41ca-98f0-abadcb11a334,XT9496056,Maximilian,Schwital,1994-07-31,männlich,"Gustav-Trubin-Weg 3-3, 17727 Cloppenburg",+49(0) 272601630,ferencschleich@example.org,ledig,Mathematiker,Marketing,31456,unbefristet,2020-12-16,III,3,MS
4,3827345c-a7d3-4ad5-bfb8-f249c754a965,NN5363995,Ella,Schuster,1970-09-07,männlich,"Steyring 6-6, 21921 Tuttlingen",+49(0) 130014789,gnatzrainer@example.net,verwitwet,Techniker,HR,118794,azubi,2024-01-13,V,24,ES
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
29995,8cb27457-479c-4cea-bed9-a281f94b105c,WG9192628,Alexei,Nette,1957-09-23,männlich,"Gesche-Thies-Weg 7-4, 59826 Staffelstein",+49 (0) 1505 132209,stephankrebs@example.org,geschieden,Pilot,IT,54179,unbefristet,2021-02-20,I,28,AN
29996,819cf7fb-8511-460b-87ae-950f45e8c0a1,BE4301155,Hanife,Geißler,1986-09-28,weiblich,"Ludmila-Hänel-Gasse 4367, 42501 Perleberg",(03228) 918494,notburga48@example.org,ledig,Friseur,Vertrieb,32587,azubi,2022-11-12,V,19,HG
29997,3eece68a-9cc2-482c-ac5b-614e9d9aab33,WV8694163,Karolin,Weller,1952-06-20,männlich,"Davidsgasse 49-18, 63071 Ahaus",(08326) 704563,natalikoehler@example.net,verheiratet,Bäcker,Marketing,78911,azubi,2024-10-06,I,1,KW
29998,60546bb4-371f-49c8-a0f1-fd11666942ee,RD5262073,Ilias,Schulz,2005-12-10,männlich,"Keudelweg 6394, 15851 Forst",00721 507538,kreingoenuel@example.com,ledig,Chirurgiemechaniker,Einkauf,30639,azubi,2023-03-30,V,25,IS
29999,b967a472-3220-4a9b-997a-a7e16e201fd2,EO9507575,Ildiko,Bähr,1979-12-06,weiblich,"Kitzmannstr. 3, 97323 Dieburg",(00582) 284760,hellwigekaterina@example.org,verheiratet,Programmierer,IT,47855,unbefristet,2025-07-02,V,13,IB

In [12]:
df.shape

(30000, 18)

In [9]:
df

,MitarbeiterID,Dienstnummer,Vorname,Nachname,Geburtsdatum,Geschlecht,Adresse,Telefon,Email,Familienstand,Beruf,Abteilung,Gehalt_m,Vertrag,Letzte Gehaltsverhandlung,Steuerklasse,Urlaubstage,Initialien
0,413885b6-da63-4e89-a887-926f6cc40b9f,NZ8637335,Nils,Ditschlerin,1963-04-06,divers,"Wellerplatz 6461, 49247 Uffenheim",06376 474749,suzannesoeding@example.com,ledig,Elektroniker,IT,86595,befristet,2020-12-16,V,24,ND
1,be400057-3025-422f-be87-d53f96a94451,GR9519484,Laura,Hornig,2002-04-27,männlich,"Adele-Davids-Gasse 55-41, 31945 Garmisch-Parte...",+49(0)0632 28106,yruppersberger@example.org,verheiratet,Florist,HR,77708,unbefristet,2022-08-17,IV,23,LH
2,aa5db6ab-e4f6-44c5-b2e6-ca14a2a4904a,CB2082368,Hellmuth,Ruppert,1967-10-15,divers,"Belinda-Beckmann-Weg 0, 60208 Bautzen",(05529) 024082,dehmelberthold@example.org,verheiratet,Fleischer,IT,33700,unbefristet,2021-06-20,VI,6,HR
3,74ad6f76-82af-41ca-98f0-abadcb11a334,XT9496056,Maximilian,Schwital,1994-07-31,männlich,"Gustav-Trubin-Weg 3-3, 17727 Cloppenburg",+49(0) 272601630,ferencschleich@example.org,ledig,Mathematiker,Marketing,31456,unbefristet,2020-12-16,III,3,MS
4,3827345c-a7d3-4ad5-bfb8-f249c754a965,NN5363995,Ella,Schuster,1970-09-07,männlich,"Steyring 6-6, 21921 Tuttlingen",+49(0) 130014789,gnatzrainer@example.net,verwitwet,Techniker,HR,118794,azubi,2024-01-13,V,24,ES
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
29995,8cb27457-479c-4cea-bed9-a281f94b105c,WG9192628,Alexei,Nette,1957-09-23,männlich,"Gesche-Thies-Weg 7-4, 59826 Staffelstein",+49 (0) 1505 132209,stephankrebs@example.org,geschieden,Pilot,IT,54179,unbefristet,2021-02-20,I,28,AN
29996,819cf7fb-8511-460b-87ae-950f45e8c0a1,BE4301155,Hanife,Geißler,1986-09-28,weiblich,"Ludmila-Hänel-Gasse 4367, 42501 Perleberg",(03228) 918494,notburga48@example.org,ledig,Friseur,Vertrieb,32587,azubi,2022-11-12,V,19,HG
29997,3eece68a-9cc2-482c-ac5b-614e9d9aab33,WV8694163,Karolin,Weller,1952-06-20,männlich,"Davidsgasse 49-18, 63071 Ahaus",(08326) 704563,natalikoehler@example.net,verheiratet,Bäcker,Marketing,78911,azubi,2024-10-06,I,1,KW
29998,60546bb4-371f-49c8-a0f1-fd11666942ee,RD5262073,Ilias,Schulz,2005-12-10,männlich,"Keudelweg 6394, 15851 Forst",00721 507538,kreingoenuel@example.com,ledig,Chirurgiemechaniker,Einkauf,30639,azubi,2023-03-30,V,25,IS
29999,b967a472-3220-4a9b-997a-a7e16e201fd2,EO9507575,Ildiko,Bähr,1979-12-06,weiblich,"Kitzmannstr. 3, 97323 Dieburg",(00582) 284760,hellwigekaterina@example.org,verheiratet,Programmierer,IT,47855,unbefristet,2025-07-02,V,13,IB