In [1]:
%pip install pandas

Requirement already satisfied: pandas in /Users/grigo/gits/seminars/gfu/Python_individuell/.venv/lib/python3.12/site-packages (2.3.1)
Requirement already satisfied: numpy>=1.26.0 in /Users/grigo/gits/seminars/gfu/Python_individuell/.venv/lib/python3.12/site-packages (from pandas) (2.3.2)
Requirement already satisfied: python-dateutil>=2.8.2 in /Users/grigo/gits/seminars/gfu/Python_individuell/.venv/lib/python3.12/site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /Users/grigo/gits/seminars/gfu/Python_individuell/.venv/lib/python3.12/site-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /Users/grigo/gits/seminars/gfu/Python_individuell/.venv/lib/python3.12/site-packages (from pandas) (2025.2)
Requirement already satisfied: six>=1.5 in /Users/grigo/gits/seminars/gfu/Python_individuell/.venv/lib/python3.12/site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Note: you may need to restart the kernel to use updated packages.

In [2]:
from faker import Faker
import random
import pandas as pd 
fake = Faker("de_DE")

In [3]:
def random_gender():
    return random.choice(["männlich", "weiblich", 'divers'])

def random_blood_type():
    return random.choice(["A+", "A-", "B+", "B-","O+", "O-","AB+","AB-"])

def random_smoker():
    return random.choice([True, False])

def random_allergies():
    return random.choice(["keine", "Pollen", "Nüsse", "Milch", "Gluten"])

def random_family_status():
    return random.choice(["ledig", "verheiratet", "geschieden", "verwitwet"])

In [4]:
patienten = []

for _ in range(50000):
    patient = {
    "PatientenID": fake.unique.uuid4(),
    "Versichertennummer": fake.bothify("??#######").upper(), # zwei Mal Buchstabe, 6 mal Zahl
    "Vorname": fake.first_name(),
    "Nachname": fake.last_name(),
    "Geburtsdatum": fake.date_of_birth(minimum_age=1, maximum_age=99),
    "Geschlecht": random_gender(),
    "Adresse": fake.address().replace('\n', ', '), # Bei Adresse die Neuzeilen durch Komma+Leerzeichen ersetzen
    "Telefon": fake.phone_number(),
    "Email": fake.unique.email(),
    "Blutgruppe": random_blood_type(),
    "Letzer_Besuch": fake.date_this_year(),
    "Hausarzt": f"{fake.first_name()} {fake.last_name()}",
    "Größe_cm":  random.randint(140, 220),
    "Gewicht_kg": random.randint(40, 130),
    "Raucher": random_smoker(),
    "Allergien": random_allergies(),
    "Letzes_EKG": fake.date_this_year(),
    "BMI": round(random.uniform(18,36),1), # Zufallszahl 
    "Familienstand": random_family_status(),
    "Beruf": fake.job(),
}
    patienten.append(patient)

patienten

[{'PatientenID': 'b24ff43e-a903-4789-b2f6-4056773e3a06',
  'Versichertennummer': 'AQ2755005',
  'Vorname': 'Svetlana',
  'Nachname': 'Scholz',
  'Geburtsdatum': datetime.date(1975, 3, 11),
  'Geschlecht': 'weiblich',
  'Adresse': 'Fechnerring 6-5, 88532 Erding',
  'Telefon': '07311 236676',
  'Email': 'heckertabea@example.net',
  'Blutgruppe': 'A-',
  'Letzer_Besuch': datetime.date(2025, 3, 1),
  'Hausarzt': 'Cäcilie Kabus',
  'Größe_cm': 149,
  'Gewicht_kg': 74,
  'Raucher': True,
  'Allergien': 'Nüsse',
  'Letzes_EKG': datetime.date(2025, 5, 29),
  'BMI': 28.4,
  'Familienstand': 'geschieden',
  'Beruf': 'Techniker'},
 {'PatientenID': 'fbffa844-ec1d-4f20-9a0b-5474dfcaf702',
  'Versichertennummer': 'XB8073653',
  'Vorname': 'Linda',
  'Nachname': 'Ackermann',
  'Geburtsdatum': datetime.date(1978, 3, 17),
  'Geschlecht': 'divers',
  'Adresse': 'Wähnerweg 7/5, 57649 Euskirchen',
  'Telefon': '+49(0)6282711059',
  'Email': 'kargerene@example.org',
  'Blutgruppe': 'AB+',
  'Letzer_Besuch': datetime.date(2025, 4, 28),
  'Hausarzt': 'Konstanze Binner',
  'Größe_cm': 190,
  'Gewicht_kg': 63,
  'Raucher': False,
  'Allergien': 'Pollen',
  'Letzes_EKG': datetime.date(2025, 4, 20),
  'BMI': 30.4,
  'Familienstand': 'ledig',
  'Beruf': 'Friseur'},
 {'PatientenID': '65d26661-3f6a-4d52-847d-d722d7d0cc25',
  'Versichertennummer': 'XC1598876',
  'Vorname': 'Karoline',
  'Nachname': 'Jüttner',
  'Geburtsdatum': datetime.date(1937, 9, 27),
  'Geschlecht': 'weiblich',
  'Adresse': 'Frida-Höfig-Ring 41/17, 37134 Dachau',
  'Telefon': '+49(0)7142 95095',
  'Email': 'joachimjunitz@example.net',
  'Blutgruppe': 'A+',
  'Letzer_Besuch': datetime.date(2025, 3, 11),
  'Hausarzt': 'Constance Hermighausen',
  'Größe_cm': 169,
  'Gewicht_kg': 68,
  'Raucher': True,
  'Allergien': 'Pollen',
  'Letzes_EKG': datetime.date(2025, 7, 10),
  'BMI': 26.5,
  'Familienstand': 'geschieden',
  'Beruf': 'Bäcker'},
 {'PatientenID': 'def9fe72-2ba0-44d8-bbf5-fe9c8df803a1',
  'Versichertennummer': 'HP3422006',
  'Vorname': 'Andrew',
  'Nachname': 'Kobelt',
  'Geburtsdatum': datetime.date(1960, 9, 23),
  'Geschlecht': 'weiblich',
  'Adresse': 'Ole-Schmiedt-Straße 38, 42082 Hechingen',
  'Telefon': '06705 142476',
  'Email': 'wilhelminelehmann@example.com',
  'Blutgruppe': 'B-',
  'Letzer_Besuch': datetime.date(2025, 3, 24),
  'Hausarzt': 'Erdogan Sauer',
  'Größe_cm': 145,
  'Gewicht_kg': 87,
  'Raucher': False,
  'Allergien': 'Milch',
  'Letzes_EKG': datetime.date(2025, 7, 25),
  'BMI': 30.6,
  'Familienstand': 'verwitwet',
  'Beruf': 'Beamter'},
 {'PatientenID': 'da1bc0e2-73bd-4ccb-abb5-0b6b180266a1',
  'Versichertennummer': 'SP6375505',
  'Vorname': 'James',
  'Nachname': 'Stiffel',
  'Geburtsdatum': datetime.date(1951, 6, 21),
  'Geschlecht': 'divers',
  'Adresse': 'Wolfgang-Förster-Gasse 65/17, 16662 Roth',
  'Telefon': '+49(0)1601 00257',
  'Email': 'ulrike39@example.org',
  'Blutgruppe': 'AB-',
  'Letzer_Besuch': datetime.date(2025, 7, 28),
  'Hausarzt': 'Marie-Therese Wiek',
  'Größe_cm': 175,
  'Gewicht_kg': 123,
  'Raucher': False,
  'Allergien': 'Milch',
  'Letzes_EKG': datetime.date(2025, 3, 10),
  'BMI': 32.7,
  'Familienstand': 'ledig',
  'Beruf': 'Chirurgiemechaniker'},
 {'PatientenID': '3cacc5de-ec2a-44f2-a340-7d3eecd3352b',
  'Versichertennummer': 'PG9563299',
  'Vorname': 'Folkert',
  'Nachname': 'Mühle',
  'Geburtsdatum': datetime.date(2004, 11, 25),
  'Geschlecht': 'divers',
  'Adresse': 'Florence-Karge-Weg 378, 32779 Forchheim',
  'Telefon': '(05372) 589718',
  'Email': 'bennodietz@example.com',
  'Blutgruppe': 'A+',
  'Letzer_Besuch': datetime.date(2025, 6, 20),
  'Hausarzt': 'Ortwin Freudenberger',
  'Größe_cm': 160,
  'Gewicht_kg': 75,
  'Raucher': False,
  'Allergien': 'Nüsse',
  'Letzes_EKG': datetime.date(2025, 1, 14),
  'BMI': 29.3,
  'Familienstand': 'verheiratet',
  'Beruf': 'Ausbaufacharbeiter'},
 {'PatientenID': 'b27d2dcc-8457-40fd-9581-7f4a8934ab3b',
  'Versichertennummer': 'OS9331247',
  'Vorname': 'Amir',
  'Nachname': 'Heß',
  'Geburtsdatum': datetime.date(1990, 10, 3),
  'Geschlecht': 'divers',
  'Adresse': 'Margret-Säuberlich-Ring 4/5, 43157 Eisenhüttenstadt',
  'Telefon': '+49 (0) 7729 632372',
  'Email': 'zwirth@example.com',
  'Blutgruppe': 'B-',
  'Letzer_Besuch': datetime.date(2025, 4, 15),
  'Hausarzt': 'Ines Dowerg',
  'Größe_cm': 210,
  'Gewicht_kg': 82,
  'Raucher': False,
  'Allergien': 'Gluten',
  'Letzes_EKG': datetime.date(2025, 2, 20),
  'BMI': 25.2,
  'Familienstand': 'verheiratet',
  'Beruf': 'Friseur'},
 {'PatientenID': '2a38c998-2412-4551-89bb-ea30fe16ea6f',
  'Versichertennummer': 'QV1422301',
  'Vorname': 'Danilo',
  'Nachname': 'Ernst',
  'Geburtsdatum': datetime.date(1994, 7, 5),
  'Geschlecht': 'weiblich',
  'Adresse': 'Trommlerplatz 27, 36800 Steinfurt',
  'Telefon': '+49(0)8941 28175',
  'Email': 'gueltenlange@example.com',
  'Blutgruppe': 'A+',
  'Letzer_Besuch': datetime.date(2025, 2, 10),
  'Hausarzt': 'Pius Bähr',
  'Größe_cm': 161,
  'Gewicht_kg': 41,
  'Raucher': False,
  'Allergien': 'Pollen',
  'Letzes_EKG': datetime.date(2025, 2, 17),
  'BMI': 31.6,
  'Familienstand': 'verheiratet',
  'Beruf': 'Koreanistiker'},
 {'PatientenID': 'e07d4739-8d34-4b46-b638-d158361066c2',
  'Versichertennummer': 'ZR6900724',
  'Vorname': 'Heiner',
  'Nachname': 'Trapp',
  'Geburtsdatum': datetime.date(1953, 9, 29),
  'Geschlecht': 'divers',
  'Adresse': 'André-Bärer-Allee 7/4, 87262 Eggenfelden',
  'Telefon': '0018694646',
  'Email': 'steckeldarko@example.org',
  'Blutgruppe': 'AB-',
  'Letzer_Besuch': datetime.date(2025, 1, 15),
  'Hausarzt': 'Gaby Bloch',
  'Größe_cm': 169,
  'Gewicht_kg': 53,
  'Raucher': True,
  'Allergien': 'Gluten',
  'Letzes_EKG': datetime.date(2025, 5, 10),
  'BMI': 21.7,
  'Familienstand': 'ledig',
  'Beruf': 'Designer'},
 {'PatientenID': 'fefaa244-30bf-4d10-a889-289393781443',
  'Versichertennummer': 'NU2272781',
  'Vorname': 'Galina',
  'Nachname': 'Gnatz',
  'Geburtsdatum': datetime.date(2018, 1, 23),
  'Geschlecht': 'divers',
  'Adresse': 'Leila-Stroh-Ring 1-4, 49414 Bischofswerda',
  'Telefon': '0765777254',
  'Email': 'karztabea@example.net',
  'Blutgruppe': 'O-',
  'Letzer_Besuch': datetime.date(2025, 1, 17),
  'Hausarzt': 'Therese Bien',
  'Größe_cm': 162,
  'Gewicht_kg': 126,
  'Raucher': True,
  'Allergien': 'Pollen',
  'Letzes_EKG': datetime.date(2025, 6, 6),
  'BMI': 27.9,
  'Familienstand': 'geschieden',
  'Beruf': 'Pfleger'},
 {'PatientenID': '87fc1d74-84c3-4c26-a11b-ef81905150bb',
  'Versichertennummer': 'DS7840745',
  'Vorname': 'Erkan',
  'Nachname': 'Wiek',
  'Geburtsdatum': datetime.date(1932, 2, 9),
  'Geschlecht': 'weiblich',
  'Adresse': 'Mustafa-Scheuermann-Gasse 1/8, 37240 Günzburg',
  'Telefon': '(04923) 056133',
  'Email': 'mustafahenck@example.com',
  'Blutgruppe': 'A-',
  'Letzer_Besuch': datetime.date(2025, 6, 14),
  'Hausarzt': 'Conrad Spieß',
  'Größe_cm': 157,
  'Gewicht_kg': 40,
  'Raucher': False,
  'Allergien': 'Gluten',
  'Letzes_EKG': datetime.date(2025, 3, 15),
  'BMI': 20.0,
  'Familienstand': 'verwitwet',
  'Beruf': 'Schornsteinfeger'},
 {'PatientenID': '6f419d89-5ccf-48ca-ad83-fe09cf8cf9ad',
  'Versichertennummer': 'EX3169327',
  'Vorname': 'Bernt',
  'Nachname': 'Löchel',
  'Geburtsdatum': datetime.date(2017, 12, 7),
  'Geschlecht': 'männlich',
  'Adresse': 'Birnbaumplatz 3189, 85557 Plauen',
  'Telefon': '+49(0)5882 75798',
  'Email': 'mohaupttorben@example.org',
  'Blutgruppe': 'AB-',
  'Letzer_Besuch': datetime.date(2025, 3, 23),
  'Hausarzt': 'Philippe Schmiedecke',
  'Größe_cm': 191,
  'Gewicht_kg': 70,
  'Raucher': True,
  'Allergien': 'Nüsse',
  'Letzes_EKG': datetime.date(2025, 6, 4),
  'BMI': 29.6,
  'Familienstand': 'verwitwet',
  'Beruf': 'Winzer'},
 {'PatientenID': 'c86a3c2c-6f70-4dc6-b2f8-5bd41e835a06',
  'Versichertennummer': 'NS9641437',
  'Vorname': 'Käthe',
  'Nachname': 'Dietz',
  'Geburtsdatum': datetime.date(2015, 3, 21),
  'Geschlecht': 'männlich',
  'Adresse': 'Adriane-Trupp-Gasse 80/53, 56129 Bad Langensalza',
  'Telefon': '+49(0)9452951978',
  'Email': 'maelzertilmann@example.com',
  'Blutgruppe': 'AB+',
  'Letzer_Besuch': datetime.date(2025, 4, 2),
  'Hausarzt': 'Bernadette Trapp',
  'Größe_cm': 194,
  'Gewicht_kg': 84,
  'Raucher': True,
  'Allergien': 'keine',
  'Letzes_EKG': datetime.date(2025, 6, 19),
  'BMI': 32.5,
  'Familienstand': 'ledig',
  'Beruf': 'Informatiker'},
 {'PatientenID': 'db5e9992-eac3-46dc-9c75-bce46e5a3f6d',
  'Versichertennummer': 'CO5981350',
  'Vorname': 'Kazim',
  'Nachname': 'Rogge',
  'Geburtsdatum': datetime.date(2007, 11, 21),
  'Geschlecht': 'männlich',
  'Adresse': 'Volkhard-Trüb-Gasse 72-17, 29122 Regensburg',
  'Telefon': '(03053) 49202',
  'Email': 'linusgeisler@example.net',
  'Blutgruppe': 'B-',
  'Letzer_Besuch': datetime.date(2025, 3, 31),
  'Hausarzt': 'Alfonso Langern',
  'Größe_cm': 189,
  'Gewicht_kg': 83,
  'Raucher': True,
  'Allergien': 'Milch',
  'Letzes_EKG': datetime.date(2025, 4, 19),
  'BMI': 23.9,
  'Familienstand': 'verheiratet',
  'Beruf': 'Pilot'},
 {'PatientenID': '8f70b024-1bde-4d27-9b58-cbff4fc5a613',
  'Versichertennummer': 'JV5170192',
  'Vorname': 'Torsten',
  'Nachname': 'Schwital',
  'Geburtsdatum': datetime.date(1981, 6, 2),
  'Geschlecht': 'divers',
  'Adresse': 'Karlfried-Ritter-Straße 61/95, 62483 Bitterfeld',
  'Telefon': '(02326) 656887',
  'Email': 'cgirschner@example.com',
  'Blutgruppe': 'A+',
  'Letzer_Besuch': datetime.date(2025, 7, 15),
  'Hausarzt': 'Irene Zorbach',
  'Größe_cm': 194,
  'Gewicht_kg': 59,
  'Raucher': True,
  'Allergien': 'Nüsse',
  'Letzes_EKG': datetime.date(2025, 2, 12),
  'BMI': 31.1,
  'Familienstand': 'geschieden',
  'Beruf': 'Fachinformatiker'},
 {'PatientenID': '81c6c9e5-1f08-4dad-9376-163fe7f072e5',
  'Versichertennummer': 'OE8035860',
  'Vorname': 'Berthold',
  'Nachname': 'Liebelt',
  'Geburtsdatum': datetime.date(1992, 2, 19),
  'Geschlecht': 'weiblich',
  'Adresse': 'Mülichenstraße 45, 81212 Neubrandenburg',
  'Telefon': '(02870) 62814',
  'Email': 'rolf52@example.org',
  'Blutgruppe': 'B+',
  'Letzer_Besuch': datetime.date(2025, 7, 25),
  'Hausarzt': 'Heinz-Günter Henck',
  'Größe_cm': 181,
  'Gewicht_kg': 111,
  'Raucher': False,
  'Allergien': 'Gluten',
  'Letzes_EKG': datetime.date(2025, 4, 2),
  'BMI': 26.8,
  'Familienstand': 'verheiratet',
  'Beruf': 'Beamter'},
 {'PatientenID': '7d360054-e350-4faf-ba50-5a1288542619',
  'Versichertennummer': 'QZ1579137',
  'Vorname': 'Emine',
  'Nachname': 'Junk',
  'Geburtsdatum': datetime.date(2015, 6, 10),
  'Geschlecht': 'divers',
  'Adresse': 'Nora-Holt-Ring 46/53, 35942 Parchim',
  'Telefon': '+49(0)3529 181494',
  'Email': 'zstadelmann@example.net',
  'Blutgruppe': 'O+',
  'Letzer_Besuch': datetime.date(2025, 5, 18),
  'Hausarzt': 'Harm Gumprich',
  'Größe_cm': 175,
  'Gewicht_kg': 70,
  'Raucher': True,
  'Allergien': 'Nüsse',
  'Letzes_EKG': datetime.date(2025, 3, 9),
  'BMI': 29.1,
  'Familienstand': 'geschieden',
  'Beruf': 'Mechaniker'},
 {'PatientenID': 'b7579515-5c2c-4a9f-8feb-78d1e1fac657',
  'Versichertennummer': 'AD9820673',
  'Vorname': 'Magnus',
  'Nachname': 'Textor',
  'Geburtsdatum': datetime.date(1927, 12, 11),
  'Geschlecht': 'divers',
  'Adresse': 'Södinggasse 16, 25207 Duderstadt',
  'Telefon': '(07267) 71295',
  'Email': 'scheelannelise@example.com',
  'Blutgruppe': 'A+',
  'Letzer_Besuch': datetime.date(2025, 1, 13),
  'Hausarzt': 'Kordula Täsche',
  'Größe_cm': 201,
  'Gewicht_kg': 110,
  'Raucher': False,
  'Allergien': 'Milch',
  'Letzes_EKG': datetime.date(2025, 4, 5),
  'BMI': 20.8,
  'Familienstand': 'ledig',
  'Beruf': 'Artist'},
 {'PatientenID': '215ce051-7960-4f1f-b823-493381dad57b',
  'Versichertennummer': 'VJ6329896',
  'Vorname': 'Henriette',
  'Nachname': 'Oderwald',
  'Geburtsdatum': datetime.date(2018, 11, 6),
  'Geschlecht': 'männlich',
  'Adresse': 'Kraushaarplatz 15-65, 18087 Kelheim',
  'Telefon': '+49(0)2510 092880',
  'Email': 'buchholzernestine@example.net',
  'Blutgruppe': 'A-',
  'Letzer_Besuch': datetime.date(2025, 3, 17),
  'Hausarzt': 'Ramazan Ullmann',
  'Größe_cm': 193,
  'Gewicht_kg': 122,
  'Raucher': True,
  'Allergien': 'Pollen',
  'Letzes_EKG': datetime.date(2025, 1, 17),
  'BMI': 20.3,
  'Familienstand': 'verheiratet',
  'Beruf': 'Elektroniker'},
 {'PatientenID': '7a4da7f2-062c-4d1a-9c99-bb9c560edd3d',
  'Versichertennummer': 'IU0320970',
  'Vorname': 'Silva',
  'Nachname': 'Bolnbach',
  'Geburtsdatum': datetime.date(1949, 11, 3),
  'Geschlecht': 'weiblich',
  'Adresse': 'Huhngasse 4/6, 32714 Coburg',
  'Telefon': '0216492076',
  'Email': 'polina43@example.net',
  'Blutgruppe': 'A+',
  'Letzer_Besuch': datetime.date(2025, 4, 29),
  'Hausarzt': 'Athanasios Zorbach',
  'Größe_cm': 170,
  'Gewicht_kg': 66,
  'Raucher': False,
  'Allergien': 'keine',
  'Letzes_EKG': datetime.date(2025, 5, 21),
  'BMI': 24.2,
  'Familienstand': 'ledig',
  'Beruf': 'Pfleger'},
 {'PatientenID': '199e4110-8fdd-486a-87eb-84c84bae1c90',
  'Versichertennummer': 'FM1272470',
  'Vorname': 'Inka',
  'Nachname': 'Ladeck',
  'Geburtsdatum': datetime.date(1962, 9, 11),
  'Geschlecht': 'divers',
  'Adresse': 'Salzring 92, 20781 Mühlhausen',
  'Telefon': '+49(0)4990856590',
  'Email': 'utz61@example.net',
  'Blutgruppe': 'AB+',
  'Letzer_Besuch': datetime.date(2025, 5, 9),
  'Hausarzt': 'Bekir Rohleder',
  'Größe_cm': 170,
  'Gewicht_kg': 63,
  'Raucher': False,
  'Allergien': 'Nüsse',
  'Letzes_EKG': datetime.date(2025, 2, 12),
  'BMI': 26.4,
  'Familienstand': 'ledig',
  'Beruf': 'Beamter'},
 {'PatientenID': '84312496-5edf-41d0-b9b6-eb5737bff66f',
  'Versichertennummer': 'WK6062172',
  'Vorname': 'Mirella',
  'Nachname': 'Segebahn',
  'Geburtsdatum': datetime.date(1969, 11, 24),
  'Geschlecht': 'weiblich',
  'Adresse': 'Walburga-Döring-Weg 743, 10568 Wittstock',
  'Telefon': '+49(0) 902883945',
  'Email': 'wirthchrista-maria@example.com',
  'Blutgruppe': 'A-',
  'Letzer_Besuch': datetime.date(2025, 3, 9),
  'Hausarzt': 'Hugo Briemer',
  'Größe_cm': 161,
  'Gewicht_kg': 44,
  'Raucher': True,
  'Allergien': 'Milch',
  'Letzes_EKG': datetime.date(2025, 1, 13),
  'BMI': 18.9,
  'Familienstand': 'verheiratet',
  'Beruf': 'Ausbaufacharbeiter'},
 {'PatientenID': '37144cd9-4897-44c0-b0a3-18f4389fd93e',
  'Versichertennummer': 'UY6806995',
  'Vorname': 'Steffi',
  'Nachname': 'Wohlgemut',
  'Geburtsdatum': datetime.date(1943, 1, 30),
  'Geschlecht': 'weiblich',
  'Adresse': 'Nada-Rust-Ring 12-47, 31149 Viechtach',
  'Telefon': '04249 479120',
  'Email': 'roman42@example.com',
  'Blutgruppe': 'AB+',
  'Letzer_Besuch': datetime.date(2025, 2, 6),
  'Hausarzt': 'Adrian Hesse',
  'Größe_cm': 191,
  'Gewicht_kg': 115,
  'Raucher': False,
  'Allergien': 'Pollen',
  'Letzes_EKG': datetime.date(2025, 6, 6),
  'BMI': 33.2,
  'Familienstand': 'ledig',
  'Beruf': 'Drogist'},
 {'PatientenID': '479804cd-a508-413b-bd80-418ad58a023a',
  'Versichertennummer': 'DW0907725',
  'Vorname': 'Martina',
  'Nachname': 'Schwital',
  'Geburtsdatum': datetime.date(1926, 2, 19),
  'Geschlecht': 'weiblich',
  'Adresse': 'Weinholdweg 8-9, 66472 Ebern',
  'Telefon': '06619813795',
  'Email': 'qfroehlich@example.org',
  'Blutgruppe': 'O-',
  'Letzer_Besuch': datetime.date(2025, 4, 1),
  'Hausarzt': 'Fedor Höfig',
  'Größe_cm': 204,
  'Gewicht_kg': 67,
  'Raucher': True,
  'Allergien': 'keine',
  'Letzes_EKG': datetime.date(2025, 3, 13),
  'BMI': 25.6,
  'Familienstand': 'verheiratet',
  'Beruf': 'Friseur'},
 {'PatientenID': '61db8cf1-19da-4a56-922f-cd9acdb3fae0',
  'Versichertennummer': 'EQ1649940',
  'Vorname': 'Caroline',
  'Nachname': 'Rogner',
  'Geburtsdatum': datetime.date(1982, 10, 30),
  'Geschlecht': 'divers',
  'Adresse': 'Reza-Scholtz-Weg 4/5, 62695 Ebern',
  'Telefon': '03439 66283',
  'Email': 'marija46@example.net',
  'Blutgruppe': 'AB-',
  'Letzer_Besuch': datetime.date(2025, 5, 19),
  'Hausarzt': 'Sandor Ruppersberger',
  'Größe_cm': 173,
  'Gewicht_kg': 119,
  'Raucher': False,
  'Allergien': 'Nüsse',
  'Letzes_EKG': datetime.date(2025, 3, 22),
  'BMI': 35.5,
  'Familienstand': 'ledig',
  'Beruf': 'Augenoptiker'},
 {'PatientenID': '1045ece6-4f93-4cd9-ac90-60ce793b72d4',
  'Versichertennummer': 'HS4688183',
  'Vorname': 'Hans-Martin',
  'Nachname': 'Kensy',
  'Geburtsdatum': datetime.date(2010, 12, 8),
  'Geschlecht': 'weiblich',
  'Adresse': 'Fröhlichstraße 3, 10536 Wunsiedel',
  'Telefon': '08193 697932',
  'Email': 'ingrid95@example.com',
  'Blutgruppe': 'A-',
  'Letzer_Besuch': datetime.date(2025, 1, 23),
  'Hausarzt': 'Ismail Cichorius',
  'Größe_cm': 141,
  'Gewicht_kg': 57,
  'Raucher': False,
  'Allergien': 'Milch',
  'Letzes_EKG': datetime.date(2025, 1, 31),
  'BMI': 28.0,
  'Familienstand': 'verheiratet',
  'Beruf': 'Asphaltbauer'},
 {'PatientenID': '8c24fc10-085a-49c6-ba2d-c65d4088cf73',
  'Versichertennummer': 'IL2343361',
  'Vorname': 'Natalja',
  'Nachname': 'Weihmann',
  'Geburtsdatum': datetime.date(1935, 4, 12),
  'Geschlecht': 'weiblich',
  'Adresse': 'Hardy-Girschner-Weg 4239, 67083 Höxter',
  'Telefon': '00951 81367',
  'Email': 'sthies@example.net',
  'Blutgruppe': 'B-',
  'Letzer_Besuch': datetime.date(2025, 2, 12),
  'Hausarzt': 'Franz Sorgatz',
  'Größe_cm': 158,
  'Gewicht_kg': 64,
  'Raucher': False,
  'Allergien': 'Gluten',
  'Letzes_EKG': datetime.date(2025, 3, 27),
  'BMI': 22.6,
  'Familienstand': 'verwitwet',
  'Beruf': 'Artist'},
 {'PatientenID': '311daa92-a636-4e52-b38a-e0f4df51bbec',
  'Versichertennummer': 'DU9214695',
  'Vorname': 'Wendelin',
  'Nachname': 'Kobelt',
  'Geburtsdatum': datetime.date(1975, 2, 25),
  'Geschlecht': 'männlich',
  'Adresse': 'Flantzstr. 703, 62312 Bergzabern',
  'Telefon': '0890098906',
  'Email': 'cjaekel@example.com',
  'Blutgruppe': 'B-',
  'Letzer_Besuch': datetime.date(2025, 7, 22),
  'Hausarzt': 'Tanja Schuchhardt',
  'Größe_cm': 178,
  'Gewicht_kg': 55,
  'Raucher': True,
  'Allergien': 'Pollen',
  'Letzes_EKG': datetime.date(2025, 1, 14),
  'BMI': 18.7,
  'Familienstand': 'verwitwet',
  'Beruf': 'Bäcker'},
 {'PatientenID': '7c23ba6c-f7fa-41a3-a747-184c036ee69b',
  'Versichertennummer': 'HA4161746',
  'Vorname': 'Raymond',
  'Nachname': 'Eberhardt',
  'Geburtsdatum': datetime.date(1959, 7, 3),
  'Geschlecht': 'weiblich',
  'Adresse': 'Klaus-Ulrich-Barth-Gasse 9, 59054 Calau',
  'Telefon': '+49 (0) 7169 712681',
  'Email': 'beiernadia@example.net',
  'Blutgruppe': 'AB+',
  'Letzer_Besuch': datetime.date(2025, 1, 2),
  'Hausarzt': 'Hardy Margraf',
  'Größe_cm': 186,
  'Gewicht_kg': 116,
  'Raucher': False,
  'Allergien': 'Milch',
  'Letzes_EKG': datetime.date(2025, 6, 16),
  'BMI': 18.3,
  'Familienstand': 'verheiratet',
  'Beruf': 'Koreanistiker'},
 {'PatientenID': '06e9edbd-20e5-403b-8ba5-377f10ba2cd3',
  'Versichertennummer': 'VD9656786',
  'Vorname': 'Monique',
  'Nachname': 'Ortmann',
  'Geburtsdatum': datetime.date(2012, 11, 26),
  'Geschlecht': 'weiblich',
  'Adresse': 'Stahrgasse 96-26, 57155 Kassel',
  'Telefon': '05071567417',
  'Email': 'hspiess@example.com',
  'Blutgruppe': 'O+',
  'Letzer_Besuch': datetime.date(2025, 1, 25),
  'Hausarzt': 'Herta Hübel',
  'Größe_cm': 167,
  'Gewicht_kg': 88,
  'Raucher': True,
  'Allergien': 'keine',
  'Letzes_EKG': datetime.date(2025, 5, 23),
  'BMI': 28.3,
  'Familienstand': 'ledig',
  'Beruf': 'Asphaltbauer'},
 {'PatientenID': '518027f0-f2a1-4742-a0e5-c0011abd321e',
  'Versichertennummer': 'XF1148128',
  'Vorname': 'Bodo',
  'Nachname': 'Oestrovsky',
  'Geburtsdatum': datetime.date(2009, 4, 3),
  'Geschlecht': 'weiblich',
  'Adresse': 'Tamara-Lehmann-Allee 37, 78098 Wolmirstedt',
  'Telefon': '06175738037',
  'Email': 'bjoernjunitz@example.org',
  'Blutgruppe': 'A+',
  'Letzer_Besuch': datetime.date(2025, 3, 25),
  'Hausarzt': 'Rigo Tschentscher',
  'Größe_cm': 155,
  'Gewicht_kg': 66,
  'Raucher': False,
  'Allergien': 'Nüsse',
  'Letzes_EKG': datetime.date(2025, 5, 14),
  'BMI': 28.9,
  'Familienstand': 'verheiratet',
  'Beruf': 'Programmierer'},
 {'PatientenID': 'a202bcb1-951f-47f3-9a2c-c14b3a71f21f',
  'Versichertennummer': 'GE4219764',
  'Vorname': 'Sieghard',
  'Nachname': 'Wiek',
  'Geburtsdatum': datetime.date(1931, 6, 20),

In [5]:
df = pd.DataFrame(patienten)
df

,PatientenID,Versichertennummer,Vorname,Nachname,Geburtsdatum,Geschlecht,Adresse,Telefon,Email,Blutgruppe,Letzer_Besuch,Hausarzt,Größe_cm,Gewicht_kg,Raucher,Allergien,Letzes_EKG,BMI,Familienstand,Beruf
0,b24ff43e-a903-4789-b2f6-4056773e3a06,AQ2755005,Svetlana,Scholz,1975-03-11,weiblich,"Fechnerring 6-5, 88532 Erding",07311 236676,heckertabea@example.net,A-,2025-03-01,Cäcilie Kabus,149,74,True,Nüsse,2025-05-29,28.4,geschieden,Techniker
1,fbffa844-ec1d-4f20-9a0b-5474dfcaf702,XB8073653,Linda,Ackermann,1978-03-17,divers,"Wähnerweg 7/5, 57649 Euskirchen",+49(0)6282711059,kargerene@example.org,AB+,2025-04-28,Konstanze Binner,190,63,False,Pollen,2025-04-20,30.4,ledig,Friseur
2,65d26661-3f6a-4d52-847d-d722d7d0cc25,XC1598876,Karoline,Jüttner,1937-09-27,weiblich,"Frida-Höfig-Ring 41/17, 37134 Dachau",+49(0)7142 95095,joachimjunitz@example.net,A+,2025-03-11,Constance Hermighausen,169,68,True,Pollen,2025-07-10,26.5,geschieden,Bäcker
3,def9fe72-2ba0-44d8-bbf5-fe9c8df803a1,HP3422006,Andrew,Kobelt,1960-09-23,weiblich,"Ole-Schmiedt-Straße 38, 42082 Hechingen",06705 142476,wilhelminelehmann@example.com,B-,2025-03-24,Erdogan Sauer,145,87,False,Milch,2025-07-25,30.6,verwitwet,Beamter
4,da1bc0e2-73bd-4ccb-abb5-0b6b180266a1,SP6375505,James,Stiffel,1951-06-21,divers,"Wolfgang-Förster-Gasse 65/17, 16662 Roth",+49(0)1601 00257,ulrike39@example.org,AB-,2025-07-28,Marie-Therese Wiek,175,123,False,Milch,2025-03-10,32.7,ledig,Chirurgiemechaniker
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
49995,0a3b1093-4663-4120-8bc2-1197ce154368,GZ1982764,Ivana,Thies,2016-05-13,divers,"Juliane-Drub-Weg 4552, 79928 Rothenburg ob der...",00210357569,weitzelreinhild@example.com,AB-,2025-03-04,Selma Pieper,206,115,True,Nüsse,2025-04-15,21.9,verwitwet,Schornsteinfeger
49996,08fa3657-bdd6-43ba-b60b-d700f670d008,XI4160721,Anke,Budig,1935-12-27,männlich,"Bolzmannallee 7-1, 50877 Borna",03151 77049,marie-louise75@example.org,AB-,2025-05-13,Erdogan Lorch,184,77,True,Nüsse,2025-02-24,28.8,verwitwet,Techniker
49997,2642b74a-a90e-4b84-8129-be66d9bcdc42,BL2954542,Moritz,Rogge,1930-04-07,weiblich,"Hans Josef-Kostolzin-Ring 98/78, 98384 Ludwigs...",(07597) 79576,theo39@example.org,AB+,2025-04-28,Nikolas Seidel,164,113,True,Gluten,2025-03-24,33.9,geschieden,Techniker
49998,907cc2ce-8c66-4e7a-87c1-5149879b67ab,TX5400491,Stephanie,Müller,1974-09-23,weiblich,"Atzlerstraße 3-1, 23288 Regensburg",00078 011735,erwinsoeding@example.com,B+,2025-01-07,Mehdi Niemeier,146,91,False,Gluten,2025-03-10,21.1,geschieden,Friseur
49999,662acc24-641b-4c63-91da-63613720c9fd,RX2993627,Hajo,Gierschner,2013-06-25,männlich,"Kristine-Pölitz-Weg 4-3, 89851 Wittenberg",+49(0)0636971893,sinaweinhage@example.net,A-,2025-07-21,Jens-Peter Koch II,185,124,True,Nüsse,2025-01-29,25.0,verwitwet,Artist

In [6]:
df.head(10) # die ersten 10 Eintragungen

,PatientenID,Versichertennummer,Vorname,Nachname,Geburtsdatum,Geschlecht,Adresse,Telefon,Email,Blutgruppe,Letzer_Besuch,Hausarzt,Größe_cm,Gewicht_kg,Raucher,Allergien,Letzes_EKG,BMI,Familienstand,Beruf
0,b24ff43e-a903-4789-b2f6-4056773e3a06,AQ2755005,Svetlana,Scholz,1975-03-11,weiblich,"Fechnerring 6-5, 88532 Erding",07311 236676,heckertabea@example.net,A-,2025-03-01,Cäcilie Kabus,149,74,True,Nüsse,2025-05-29,28.4,geschieden,Techniker
1,fbffa844-ec1d-4f20-9a0b-5474dfcaf702,XB8073653,Linda,Ackermann,1978-03-17,divers,"Wähnerweg 7/5, 57649 Euskirchen",+49(0)6282711059,kargerene@example.org,AB+,2025-04-28,Konstanze Binner,190,63,False,Pollen,2025-04-20,30.4,ledig,Friseur
2,65d26661-3f6a-4d52-847d-d722d7d0cc25,XC1598876,Karoline,Jüttner,1937-09-27,weiblich,"Frida-Höfig-Ring 41/17, 37134 Dachau",+49(0)7142 95095,joachimjunitz@example.net,A+,2025-03-11,Constance Hermighausen,169,68,True,Pollen,2025-07-10,26.5,geschieden,Bäcker
3,def9fe72-2ba0-44d8-bbf5-fe9c8df803a1,HP3422006,Andrew,Kobelt,1960-09-23,weiblich,"Ole-Schmiedt-Straße 38, 42082 Hechingen",06705 142476,wilhelminelehmann@example.com,B-,2025-03-24,Erdogan Sauer,145,87,False,Milch,2025-07-25,30.6,verwitwet,Beamter
4,da1bc0e2-73bd-4ccb-abb5-0b6b180266a1,SP6375505,James,Stiffel,1951-06-21,divers,"Wolfgang-Förster-Gasse 65/17, 16662 Roth",+49(0)1601 00257,ulrike39@example.org,AB-,2025-07-28,Marie-Therese Wiek,175,123,False,Milch,2025-03-10,32.7,ledig,Chirurgiemechaniker
5,3cacc5de-ec2a-44f2-a340-7d3eecd3352b,PG9563299,Folkert,Mühle,2004-11-25,divers,"Florence-Karge-Weg 378, 32779 Forchheim",(05372) 589718,bennodietz@example.com,A+,2025-06-20,Ortwin Freudenberger,160,75,False,Nüsse,2025-01-14,29.3,verheiratet,Ausbaufacharbeiter
6,b27d2dcc-8457-40fd-9581-7f4a8934ab3b,OS9331247,Amir,Heß,1990-10-03,divers,"Margret-Säuberlich-Ring 4/5, 43157 Eisenhütten...",+49 (0) 7729 632372,zwirth@example.com,B-,2025-04-15,Ines Dowerg,210,82,False,Gluten,2025-02-20,25.2,verheiratet,Friseur
7,2a38c998-2412-4551-89bb-ea30fe16ea6f,QV1422301,Danilo,Ernst,1994-07-05,weiblich,"Trommlerplatz 27, 36800 Steinfurt",+49(0)8941 28175,gueltenlange@example.com,A+,2025-02-10,Pius Bähr,161,41,False,Pollen,2025-02-17,31.6,verheiratet,Koreanistiker
8,e07d4739-8d34-4b46-b638-d158361066c2,ZR6900724,Heiner,Trapp,1953-09-29,divers,"André-Bärer-Allee 7/4, 87262 Eggenfelden",0018694646,steckeldarko@example.org,AB-,2025-01-15,Gaby Bloch,169,53,True,Gluten,2025-05-10,21.7,ledig,Designer
9,fefaa244-30bf-4d10-a889-289393781443,NU2272781,Galina,Gnatz,2018-01-23,divers,"Leila-Stroh-Ring 1-4, 49414 Bischofswerda",0765777254,karztabea@example.net,O-,2025-01-17,Therese Bien,162,126,True,Pollen,2025-06-06,27.9,geschieden,Pfleger

In [7]:
df.tail(10) # die letzten 10 Eintragungen

,PatientenID,Versichertennummer,Vorname,Nachname,Geburtsdatum,Geschlecht,Adresse,Telefon,Email,Blutgruppe,Letzer_Besuch,Hausarzt,Größe_cm,Gewicht_kg,Raucher,Allergien,Letzes_EKG,BMI,Familienstand,Beruf
49990,d76a4a2f-a5f4-44b7-8f4b-609c076658fc,FM1513899,Cemal,Freudenberger,1926-03-25,weiblich,"Tschentscherstraße 7069, 56040 Schweinfurt",(03601) 23997,hesserose-marie@example.net,B-,2025-02-01,Alina Kade,169,63,True,Nüsse,2025-05-01,29.4,ledig,Augenoptiker
49991,861715d2-18ec-4b14-9827-9bae97be18e8,VN3072779,Hans-Werner,Kraus,1934-01-13,weiblich,"Otmar-Stiebitz-Ring 58/72, 26753 Moers",+49(0)4508 27715,tamararoemer@example.org,O+,2025-03-30,Andrea Benthin,140,66,False,Milch,2025-02-01,21.4,ledig,Binnenschiffer
49992,8fdeb78b-fe41-4738-8878-ffb5a969b307,MS6815126,Marcella,Paffrath,1998-06-08,divers,"Amir-Beer-Allee 54-33, 58055 Herzberg",(02132) 254350,gottfriedtrupp@example.com,B-,2025-02-15,Rebekka Segebahn,152,56,True,keine,2025-07-05,31.3,verwitwet,Fachinformatiker
49993,eacb19e2-3bff-4125-ba80-e1b32b55440e,RS9213272,Hans-J.,Adolph,1955-01-07,divers,"Emma-Kramer-Platz 11/64, 13647 Miesbach",00579165394,aloisia03@example.com,AB+,2025-05-22,Svea Bonbach,167,67,True,keine,2025-03-18,25.0,verheiratet,Mechaniker
49994,ec73061e-d38d-4e34-8914-3e730c453a99,OO3005668,Jacob,Ullmann,1988-07-22,weiblich,"Textorweg 6-9, 96490 Meiningen",+49(0)4737 309581,oliebelt@example.org,A+,2025-07-26,Andreas Lehmann,175,128,True,Milch,2025-03-26,24.8,verheiratet,Programmierer
49995,0a3b1093-4663-4120-8bc2-1197ce154368,GZ1982764,Ivana,Thies,2016-05-13,divers,"Juliane-Drub-Weg 4552, 79928 Rothenburg ob der...",00210357569,weitzelreinhild@example.com,AB-,2025-03-04,Selma Pieper,206,115,True,Nüsse,2025-04-15,21.9,verwitwet,Schornsteinfeger
49996,08fa3657-bdd6-43ba-b60b-d700f670d008,XI4160721,Anke,Budig,1935-12-27,männlich,"Bolzmannallee 7-1, 50877 Borna",03151 77049,marie-louise75@example.org,AB-,2025-05-13,Erdogan Lorch,184,77,True,Nüsse,2025-02-24,28.8,verwitwet,Techniker
49997,2642b74a-a90e-4b84-8129-be66d9bcdc42,BL2954542,Moritz,Rogge,1930-04-07,weiblich,"Hans Josef-Kostolzin-Ring 98/78, 98384 Ludwigs...",(07597) 79576,theo39@example.org,AB+,2025-04-28,Nikolas Seidel,164,113,True,Gluten,2025-03-24,33.9,geschieden,Techniker
49998,907cc2ce-8c66-4e7a-87c1-5149879b67ab,TX5400491,Stephanie,Müller,1974-09-23,weiblich,"Atzlerstraße 3-1, 23288 Regensburg",00078 011735,erwinsoeding@example.com,B+,2025-01-07,Mehdi Niemeier,146,91,False,Gluten,2025-03-10,21.1,geschieden,Friseur
49999,662acc24-641b-4c63-91da-63613720c9fd,RX2993627,Hajo,Gierschner,2013-06-25,männlich,"Kristine-Pölitz-Weg 4-3, 89851 Wittenberg",+49(0)0636971893,sinaweinhage@example.net,A-,2025-07-21,Jens-Peter Koch II,185,124,True,Nüsse,2025-01-29,25.0,verwitwet,Artist

In [8]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 50000 entries, 0 to 49999
Data columns (total 20 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   PatientenID         50000 non-null  object
 1   Versichertennummer  50000 non-null  object
 2   Vorname             50000 non-null  object
 3   Nachname            50000 non-null  object
 4   Geburtsdatum        50000 non-null  object
 5   Geschlecht          50000 non-null  object
 6   Adresse             50000 non-null  object
 7   Telefon             50000 non-null  object
 8   Email               50000 non-null  object
 9   Blutgruppe          50000 non-null  object
 10  Letzer_Besuch       50000 non-null  object
 11  Hausarzt            50000 non-null  object
 12  Größe_cm            50000 non-null  int64
 13  Gewicht_kg          50000 non-null  int64
 14  Raucher             50000 non-null  bool
 15  Allergien           50000 non-null  object
 16  Letzes_EKG          50000 non-null  object
 17  BMI                 50000 non-null  float64
 18  Familienstand       50000 non-null  object
 19  Beruf               50000 non-null  object
dtypes: bool(1), float64(1), int64(2), object(16)
memory usage: 7.3+ MB

In [9]:
df.BMI

0        28.4
1        30.4
2        26.5
3        30.6
4        32.7
         ...
49995    21.9
49996    28.8
49997    33.9
49998    21.1
49999    25.0
Name: BMI, Length: 50000, dtype: float64

In [10]:
df[["Vorname","Nachname","Geburtsdatum"]] # Zugriff auf mehrere Spalten

         Vorname    Nachname Geburtsdatum
0       Svetlana      Scholz   1975-03-11
1          Linda   Ackermann   1978-03-17
2       Karoline     Jüttner   1937-09-27
3         Andrew      Kobelt   1960-09-23
4          James     Stiffel   1951-06-21
...          ...         ...          ...
49995      Ivana       Thies   2016-05-13
49996       Anke       Budig   1935-12-27
49997     Moritz       Rogge   1930-04-07
49998  Stephanie      Müller   1974-09-23
49999       Hajo  Gierschner   2013-06-25

[50000 rows x 3 columns]

In [11]:
n_df = df[["Vorname","Nachname","Geburtsdatum"]].copy() # tiefe Kopie
n_df["Alter"] = pd.Timestamp("now").year - pd.to_datetime(n_df["Geburtsdatum"]).dt.year
n_df["Geschlecht"] = df["Geschlecht"]
n_df["Raucher"] = df["Raucher"]
# Frauen zwischen 18 und 30, Nichtraucherin
n_df[(n_df["Alter"] >= 18) & (n_df["Alter"] < 30) & (n_df["Geschlecht"] == "weiblich") & (~ n_df["Raucher"])].head()

         Vorname     Nachname Geburtsdatum  Alter Geschlecht  Raucher
113    Valentine       Zimmer   2002-11-30     23   weiblich    False
166     Hubertus     Buchholz   2003-09-29     22   weiblich    False
205      Tatiana       Hethur   2004-03-20     21   weiblich    False
216  Hans-Ludwig     Fröhlich   2006-07-27     19   weiblich    False
241     Hans-Uwe  Ditschlerin   2005-03-16     20   weiblich    False

In [12]:
n_df["BMI"] = df["BMI"]

def bmi_class(bmi):
    if bmi < 18.5:
        return "Untergewicht"
    elif bmi < 25:
        return "Normalgewicht"
    elif bmi < 30:
        return "Übergewicht"
    else:
        return "Adipositas"

n_df["BMI_Klasse"] = n_df["BMI"].apply(lambda bmi: bmi_class(bmi))

# Aufgabe: 
# Berechnen Sie die Altersgruppen als neue Spalte in n_df
# "Kind" (unter 18), "Erwachsen", "Senior" (ab 65)

def altersgruppe(alter):
    if alter<18:
        return "Kind"
    elif alter < 65:
        return "Erwachsen"
    else:
        return "Senior"

n_df["Altersgruppe"] = n_df["Alter"].apply(lambda alter: altersgruppe(alter))
n_df

,Vorname,Nachname,Geburtsdatum,Alter,Geschlecht,Raucher,BMI,BMI_Klasse,Altersgruppe
0,Svetlana,Scholz,1975-03-11,50,weiblich,True,28.4,Übergewicht,Erwachsen
1,Linda,Ackermann,1978-03-17,47,divers,False,30.4,Adipositas,Erwachsen
2,Karoline,Jüttner,1937-09-27,88,weiblich,True,26.5,Übergewicht,Senior
3,Andrew,Kobelt,1960-09-23,65,weiblich,False,30.6,Adipositas,Senior
4,James,Stiffel,1951-06-21,74,divers,False,32.7,Adipositas,Senior
...,...,...,...,...,...,...,...,...,...
49995,Ivana,Thies,2016-05-13,9,divers,True,21.9,Normalgewicht,Kind
49996,Anke,Budig,1935-12-27,90,männlich,True,28.8,Übergewicht,Senior
49997,Moritz,Rogge,1930-04-07,95,weiblich,True,33.9,Adipositas,Senior
49998,Stephanie,Müller,1974-09-23,51,weiblich,False,21.1,Normalgewicht,Erwachsen
49999,Hajo,Gierschner,2013-06-25,12,männlich,True,25.0,Übergewicht,Kind

In [13]:
def filter_normalgewicht(df):
    return df[df["BMI_Klasse"] == "Normalgewicht"]

def filter_altersgruppe(df,altersgruppe):
    return df[df["Altersgruppe"] == altersgruppe]



def blutgruppe_part(df,col):
    df["Blutgruppe"] = col
    return df[(df["Blutgruppe"]=="0+") | (df["Blutgruppe"] == "AB+")]



df_normalgewicht = (n_df
    .pipe(filter_normalgewicht)
    .sort_values("Alter", ascending =False)
)
# Data Transformation Pipeline
df_normerwachsen = (n_df
    .pipe(filter_normalgewicht)
    .pipe(filter_altersgruppe, "Erwachsen")
    .sort_values("Alter", ascending =False)
)
df_normerwachsen

,Vorname,Nachname,Geburtsdatum,Alter,Geschlecht,Raucher,BMI,BMI_Klasse,Altersgruppe
14187,Wilfriede,Paffrath,1961-12-20,64,weiblich,True,20.3,Normalgewicht,Erwachsen
49613,Regine,Köster,1961-12-20,64,divers,True,18.8,Normalgewicht,Erwachsen
49597,Yvette,Hoffmann,1961-01-12,64,weiblich,False,18.8,Normalgewicht,Erwachsen
10852,Jozef,Tröst,1961-11-30,64,weiblich,True,22.8,Normalgewicht,Erwachsen
6149,Korbinian,Jungfer,1961-05-25,64,männlich,False,21.7,Normalgewicht,Erwachsen
...,...,...,...,...,...,...,...,...,...
20333,Micha,Naser,2007-02-12,18,weiblich,True,20.5,Normalgewicht,Erwachsen
20285,Rudi,Gunpf,2007-03-02,18,divers,False,23.5,Normalgewicht,Erwachsen
20237,Johanna,Zimmer,2007-04-07,18,divers,True,20.5,Normalgewicht,Erwachsen
19880,Frederike,Bender,2007-09-30,18,divers,True,21.9,Normalgewicht,Erwachsen
13,Kazim,Rogge,2007-11-21,18,männlich,True,23.9,Normalgewicht,Erwachsen

In [14]:
# Aufgabe: 
# Schreiben Sie eine Pipeline, welche eine Spalte Blutgruppe zum df hinzufügt, nach Blutgruppe 0+ oder AB+ filtert und nur Kinder anzeigt.
# Wenden Sie die Pipeline auf n_df an.   

df_ = (n_df
    .pipe(blutgruppe_part,df["Blutgruppe"])
    .pipe(filter_altersgruppe, "Kind")
)

df_

,Vorname,Nachname,Geburtsdatum,Alter,Geschlecht,Raucher,BMI,BMI_Klasse,Altersgruppe,Blutgruppe
12,Käthe,Dietz,2015-03-21,10,männlich,True,32.5,Adipositas,Kind,AB+
75,Axel,Linke,2010-11-03,15,weiblich,False,27.0,Übergewicht,Kind,AB+
159,Silvester,Girschner,2011-04-07,14,weiblich,True,26.2,Übergewicht,Kind,AB+
164,Ahmad,Klapp,2021-07-05,4,divers,False,35.7,Adipositas,Kind,AB+
209,Gülsen,Haering,2018-11-12,7,weiblich,False,34.3,Adipositas,Kind,AB+
...,...,...,...,...,...,...,...,...,...,...
49785,Cora,Reinhardt,2024-04-30,1,weiblich,True,29.8,Übergewicht,Kind,AB+
49796,Cord,Hoffmann,2014-10-15,11,divers,True,21.8,Normalgewicht,Kind,AB+
49832,Hendrik,Krein,2018-10-11,7,männlich,False,19.3,Normalgewicht,Kind,AB+
49852,Anett,Pechel,2015-11-29,10,divers,False,32.7,Adipositas,Kind,AB+
49877,Carmine,Kallert,2017-10-14,8,weiblich,True,20.8,Normalgewicht,Kind,AB+

In [15]:
# Query - SQL-ähnliches Filtern
# Männer, BMI>30

n_df.query("Geschlecht == 'männlich' and BMI > 30")

,Vorname,Nachname,Geburtsdatum,Alter,Geschlecht,Raucher,BMI,BMI_Klasse,Altersgruppe,Blutgruppe
12,Käthe,Dietz,2015-03-21,10,männlich,True,32.5,Adipositas,Kind,AB+
32,Karl-Josef,Bauer,1995-09-20,30,männlich,True,33.5,Adipositas,Erwachsen,A+
46,Ingrid,Beer,1953-07-08,72,männlich,True,32.9,Adipositas,Senior,O+
54,Wojciech,Margraf,1934-09-02,91,männlich,True,34.3,Adipositas,Senior,A+
65,Hans-Michael,Gnatz,1927-12-20,98,männlich,False,34.3,Adipositas,Senior,B-
...,...,...,...,...,...,...,...,...,...,...
49945,Undine,Kallert,1984-12-21,41,männlich,False,33.7,Adipositas,Erwachsen,B+
49958,Nadeshda,Heuser,2007-05-20,18,männlich,False,30.5,Adipositas,Erwachsen,B+
49960,Marliese,Wagenknecht,1998-10-28,27,männlich,False,33.4,Adipositas,Erwachsen,O+
49969,Jaroslaw,Otto,1980-04-20,45,männlich,False,33.3,Adipositas,Erwachsen,B-
49975,Traute,Lindau,1987-04-01,38,männlich,True,34.4,Adipositas,Erwachsen,A-

In [24]:
df

,PatientenID,Versichertennummer,Vorname,Nachname,Geburtsdatum,Geschlecht,Adresse,Telefon,Email,Blutgruppe,Letzer_Besuch,Hausarzt,Größe_cm,Gewicht_kg,Raucher,Allergien,Letzes_EKG,BMI,Familienstand,Beruf
0,b24ff43e-a903-4789-b2f6-4056773e3a06,AQ2755005,Svetlana,Scholz,1975-03-11,weiblich,"Fechnerring 6-5, 88532 Erding",07311 236676,heckertabea@example.net,A-,2025-03-01,Cäcilie Kabus,149,74,True,Nüsse,2025-05-29,28.4,geschieden,Techniker
1,fbffa844-ec1d-4f20-9a0b-5474dfcaf702,XB8073653,Linda,Ackermann,1978-03-17,divers,"Wähnerweg 7/5, 57649 Euskirchen",+49(0)6282711059,kargerene@example.org,AB+,2025-04-28,Konstanze Binner,190,63,False,Pollen,2025-04-20,30.4,ledig,Friseur
2,65d26661-3f6a-4d52-847d-d722d7d0cc25,XC1598876,Karoline,Jüttner,1937-09-27,weiblich,"Frida-Höfig-Ring 41/17, 37134 Dachau",+49(0)7142 95095,joachimjunitz@example.net,A+,2025-03-11,Constance Hermighausen,169,68,True,Pollen,2025-07-10,26.5,geschieden,Bäcker
3,def9fe72-2ba0-44d8-bbf5-fe9c8df803a1,HP3422006,Andrew,Kobelt,1960-09-23,weiblich,"Ole-Schmiedt-Straße 38, 42082 Hechingen",06705 142476,wilhelminelehmann@example.com,B-,2025-03-24,Erdogan Sauer,145,87,False,Milch,2025-07-25,30.6,verwitwet,Beamter
4,da1bc0e2-73bd-4ccb-abb5-0b6b180266a1,SP6375505,James,Stiffel,1951-06-21,divers,"Wolfgang-Förster-Gasse 65/17, 16662 Roth",+49(0)1601 00257,ulrike39@example.org,AB-,2025-07-28,Marie-Therese Wiek,175,123,False,Milch,2025-03-10,32.7,ledig,Chirurgiemechaniker
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
49995,0a3b1093-4663-4120-8bc2-1197ce154368,GZ1982764,Ivana,Thies,2016-05-13,divers,"Juliane-Drub-Weg 4552, 79928 Rothenburg ob der...",00210357569,weitzelreinhild@example.com,AB-,2025-03-04,Selma Pieper,206,115,True,Nüsse,2025-04-15,21.9,verwitwet,Schornsteinfeger
49996,08fa3657-bdd6-43ba-b60b-d700f670d008,XI4160721,Anke,Budig,1935-12-27,männlich,"Bolzmannallee 7-1, 50877 Borna",03151 77049,marie-louise75@example.org,AB-,2025-05-13,Erdogan Lorch,184,77,True,Nüsse,2025-02-24,28.8,verwitwet,Techniker
49997,2642b74a-a90e-4b84-8129-be66d9bcdc42,BL2954542,Moritz,Rogge,1930-04-07,weiblich,"Hans Josef-Kostolzin-Ring 98/78, 98384 Ludwigs...",(07597) 79576,theo39@example.org,AB+,2025-04-28,Nikolas Seidel,164,113,True,Gluten,2025-03-24,33.9,geschieden,Techniker
49998,907cc2ce-8c66-4e7a-87c1-5149879b67ab,TX5400491,Stephanie,Müller,1974-09-23,weiblich,"Atzlerstraße 3-1, 23288 Regensburg",00078 011735,erwinsoeding@example.com,B+,2025-01-07,Mehdi Niemeier,146,91,False,Gluten,2025-03-10,21.1,geschieden,Friseur
49999,662acc24-641b-4c63-91da-63613720c9fd,RX2993627,Hajo,Gierschner,2013-06-25,männlich,"Kristine-Pölitz-Weg 4-3, 89851 Wittenberg",+49(0)0636971893,sinaweinhage@example.net,A-,2025-07-21,Jens-Peter Koch II,185,124,True,Nüsse,2025-01-29,25.0,verwitwet,Artist

In [40]:
# Gruppenweise Mittelwerte

agg_df = df.groupby(["Geschlecht", "Raucher"])[["Größe_cm", "Gewicht_kg", "BMI" ]].agg(
    [
        'mean', 
        'std',  # Standartabweichung
        'min', 
        'max',
    ]
) 

agg_df["Gewicht_kg"]["std"]

Geschlecht  Raucher
divers      False      26.326542
            True       26.153594
männlich    False      26.232996
            True       26.329325
weiblich    False      26.254280
            True       26.271550
Name: std, dtype: float64

In [42]:
df.groupby(["Geschlecht", "Raucher"])[["Größe_cm", "Gewicht_kg", "BMI" ]].agg(
    {
        "Größe_cm": "mean",
        "Gewicht_kg": "mean",
        "BMI": "max",
    }
)

                      Größe_cm  Gewicht_kg   BMI
Geschlecht Raucher
divers     False    179.357433   85.124044  36.0
           True     180.352687   85.193618  36.0
männlich   False    179.794984   85.073481  36.0
           True     179.808477   85.357056  36.0
weiblich   False    180.435711   85.554343  36.0
           True     179.723637   84.833413  36.0

In [ ]:
# Aufgabe: 
# 1. Erstellen Sie eine Statistik zur durchschnittlichen Größe und Gewicht 
# je nach Altersgruppe. 
# 2. Geben Sie Altersgruppen mit durchschnittlichen Gewicht >= 85.1 an
df["Alter"] = pd.Timestamp("now").year - pd.to_datetime(n_df["Geburtsdatum"]).dt.year
df["Altersgruppe"] = df["Alter"].apply(lambda alter: altersgruppe(alter))


agg_df = df.groupby(["Altersgruppe"])[["Größe_cm", "Gewicht_kg" ]].mean()
agg_df[agg_df["Gewicht_kg"]>85.1]

                Größe_cm  Gewicht_kg
Altersgruppe
Erwachsen     179.994841   85.190088
Senior        179.804691   85.226063

In [ ]:
agg_df.loc["Kind"] # Zeile auswählen
agg_df.loc["Kind", "Größe_cm"] # Wert in der Zeile "Kind" und Spalte "Größe_cm"
agg_df.loc[:,"Gewicht_kg"] # Spaltenauswahl in der Matrixnotation
agg_df.loc["Erwachsen":"Kind",:] # Slicing
df.loc[:500,"Vorname":] # Alle Spalten von "Vornamen" bis Ende, die ersten 500 Zeilen
df.loc[:,:"Raucher"] # alle Spalten bis "Raucher"
df.loc[100:200,"Hausarzt":"Familienstand"] # Zeile 100 bis Zeile 200, Spalte "Hausarzt" bis Spalte "Familienstand"

,Hausarzt,Größe_cm,Gewicht_kg,Raucher,Allergien,Letzes_EKG,BMI,Familienstand
100,Franz-Josef Trommler,168,114,True,Nüsse,2025-05-08,20.4,verheiratet
101,Josip Schleich,205,125,False,keine,2025-01-19,23.7,verheiratet
102,Jane Karge,156,122,True,keine,2025-02-28,25.6,verwitwet
103,Sylwia Ritter,204,123,False,Nüsse,2025-05-20,22.9,verheiratet
104,Kathi Jähn,144,76,True,Pollen,2025-03-11,33.5,verwitwet
...,...,...,...,...,...,...,...,...
196,Anne-Katrin Gorlitz,175,122,True,Nüsse,2025-05-14,29.1,verheiratet
197,Dietrich Siering,147,70,True,keine,2025-03-15,31.0,ledig
198,Katy Dietz,142,107,True,Gluten,2025-03-17,32.2,ledig
199,Vitus Kohl,148,114,False,Nüsse,2025-04-20,31.6,verwitwet
200,Irmela Hellwig,141,122,False,Pollen,2025-07-29,21.0,geschieden

In [90]:
# komplexere Auswahl

df.loc[[5,10],["Allergien","Größe_cm"]].loc[df["Alter"]>25]

   Allergien  Größe_cm
10    Gluten       157

In [ ]:
df.loc[5,"Größe_cm"]
df.at[5,"Größe_cm"] # empfohlen bei Zugriff auf Einzelwerte
df.loc[5,"Größe_cm"] = 166  # Zuweisung
df.at[5,"Größe_cm"]

np.int64(166)

In [94]:
agg_df

                Größe_cm  Gewicht_kg
Altersgruppe
Erwachsen     179.994841   85.190088
Kind          179.901982   85.098743
Senior        179.804691   85.226063

In [105]:
agg_df.iloc[1] # Zeile auswählen
agg_df.iloc[1, 0] # Wert in der Zeile "Kind" und Spalte "Größe_cm"
agg_df.iloc[:,1] # Spaltenauswahl in der Matrixnotation
agg_df.iloc[0:2,:] # Slicing
df.iloc[:500,2:] # Alle Spalten von "Vornamen" bis Ende, die ersten 500 Zeilen
df.iloc[:,:15] # alle Spalten bis "Raucher"
df.iloc[100:200,11:19] # Zeile 100 bis Zeile 200, Spalte "Hausarzt" bis Spalte "Familienstand"

,Hausarzt,Größe_cm,Gewicht_kg,Raucher,Allergien,Letzes_EKG,BMI,Familienstand
100,Franz-Josef Trommler,168,114,True,Nüsse,2025-05-08,20.4,verheiratet
101,Josip Schleich,205,125,False,keine,2025-01-19,23.7,verheiratet
102,Jane Karge,156,122,True,keine,2025-02-28,25.6,verwitwet
103,Sylwia Ritter,204,123,False,Nüsse,2025-05-20,22.9,verheiratet
104,Kathi Jähn,144,76,True,Pollen,2025-03-11,33.5,verwitwet
...,...,...,...,...,...,...,...,...
195,Axel Werner,179,108,True,Milch,2025-06-21,28.1,verheiratet
196,Anne-Katrin Gorlitz,175,122,True,Nüsse,2025-05-14,29.1,verheiratet
197,Dietrich Siering,147,70,True,keine,2025-03-15,31.0,ledig
198,Katy Dietz,142,107,True,Gluten,2025-03-17,32.2,ledig
199,Vitus Kohl,148,114,False,Nüsse,2025-04-20,31.6,verwitwet

In [ ]:
df.to_pickle("patient.pk") # Pickle = binäres Serialisierungsformat
# Verwenden Sie nicht, wenn Sie nicht wissen wer und wie die Pickle-Datei
# erstellt worden ist.