In [1]:
import pandas as pd
from faker import Faker
import random

In [2]:
fake = Faker("de_DE")

def random_gender():
    return random.choice(["männlich", "weiblich", 'divers'])

def random_abteilung():
    return random.choice(["IT", "HR", "Vertrieb", "Marketing", "Einkauf"])

def random_contract():
    return random.choice(["befristet", "unbefristet", "azubi"])

def random_tax_class():
    return random.choice(["I", "II", "III", "IV", "V", "VI"])

def random_family_status():
    return random.choice(["ledig", "verheiratet", "geschieden", "verwitwet"])

In [3]:
rows = []

for _ in range(30000):
    mitarbeiter = {
        "MitarbeiterID": fake.unique.uuid4(),
        "Dienstnummer": fake.bothify("??#######").upper(), # zwei Mal Buchstabe, 6 mal Zahl
        "Vorname": fake.first_name(),
        "Nachname": fake.last_name(),
        "Geburtsdatum": fake.date_of_birth(minimum_age=18, maximum_age=75),
        "Geschlecht": random_gender(),
        "Adresse": fake.address().replace('\n', ', '), # Bei Adresse die Neuzeilen durch Komma+Leerzeichen ersetzen
        "Telefon": fake.phone_number(),
        "Email": fake.unique.email(),
        "Familienstand": random_family_status(),
        "Beruf": fake.job(),
        "Abteilung":  random_abteilung(),
        "Gehalt_m":random.randint(27000,120000),
        "Vertrag": random_contract(),
        "Letzte Gehaltsverhandlung": fake.date_between(start_date="-5y", end_date="today"), 
        "Steuerklasse": random_tax_class(),
    }
    rows.append(mitarbeiter)

df = pd.DataFrame(rows)

In [4]:
df.head()

,MitarbeiterID,Dienstnummer,Vorname,Nachname,Geburtsdatum,Geschlecht,Adresse,Telefon,Email,Familienstand,Beruf,Abteilung,Gehalt_m,Vertrag,Letzte Gehaltsverhandlung,Steuerklasse
0,6fa3cad1-a901-46fc-9b2e-44e170102f0f,HN6431264,Heinfried,Höfig,1967-02-05,divers,"Bärerplatz 46-37, 10264 Lemgo",+49(0)6651 91139,guenther55@example.org,ledig,Altenpfleger,Marketing,101902,befristet,2025-01-04,V
1,54241c49-5d57-4260-8b9a-b39bd82e3596,QX3370028,Sigmar,Thies,1990-02-26,männlich,"Möchlichenstr. 9-2, 57857 Stendal",0961256094,auch-schlauchinadina@example.net,verheiratet,Winzer,Marketing,109952,azubi,2023-11-24,I
2,1cc23984-d455-4089-a7ce-9c073e8fd4a6,YO9477396,Reiner,Ehlert,1986-03-26,weiblich,"Melita-Otto-Weg 4-9, 16909 Güstrow",05238 36756,lindaurenato@example.net,verwitwet,Ausbaufacharbeiter,Einkauf,112739,azubi,2025-01-21,V
3,81dacbc0-6156-4114-9b94-4d6a39102368,CU6669641,Mustafa,Löwer,1967-07-06,männlich,"Boucseinstr. 12, 44938 Riesa",+49(0)3668 79991,hofmannpawel@example.net,ledig,Arzt,HR,51716,befristet,2020-09-06,V
4,28a0a5f2-3a12-44b7-b392-5faabc5453f7,HU4719971,Dajana,Briemer,1993-11-28,weiblich,"Ritterstraße 99, 81748 Mellrichstadt",+49 (0) 2003 128137,katysegebahn@example.org,verheiratet,Altenpfleger,Einkauf,88858,azubi,2020-12-05,VI

# Zweites DataFrame: Fortbildungmaßnahmen

In [5]:
fortbildungs_ids = df["MitarbeiterID"].sample(frac=0.2, random_state = 1)

def random_possibilities():
    return random.choice(["SCRUM", "ISO9001", "Datenschutz", "Leadership", "Python Fortgeschritten", "Java"])

fortb_list = []

for id in fortbildungs_ids:
    eintrag = {
        "MitarbeiterID": id,
        "Fortbildung": random_possibilities(),
        "Dauer_d": random.randint(1,7),
        "Abschluss": random.choice([True, False]),
        "Durchgeführt_am": fake.date_this_year(),
    }
    fortb_list.append(eintrag)

df2 = pd.DataFrame(fortb_list)
df2

,MitarbeiterID,Fortbildung,Dauer_d,Abschluss,Durchgeführt_am
0,2cb48cb7-27d2-4b48-bf34-a8b8adaf5e8e,Datenschutz,3,False,2025-06-29
1,cb6d0da8-1b9c-4e04-b829-24c98959da4e,ISO9001,5,True,2025-06-23
2,17a12a81-6426-4eb5-a6ae-40d58ee41edc,Leadership,7,True,2025-06-27
3,85a96a66-f09a-4248-ba36-9354c83543e5,ISO9001,1,False,2025-06-18
4,c20c5a72-78e8-42e0-8428-3bab47db7da6,ISO9001,1,True,2025-02-17
...,...,...,...,...,...
5995,2a8028bb-9722-4e32-a598-706011777e45,Python Fortgeschritten,2,True,2025-07-09
5996,9625c1ba-94b6-4100-98d0-e37a425baec4,Java,7,True,2025-07-08
5997,550eed12-7425-46b4-a13d-5fc1791e08d4,Python Fortgeschritten,3,True,2025-04-27
5998,1b40b45f-b870-4510-8458-1988fedcc544,Datenschutz,1,True,2025-01-19
5999,fdaef3b1-4f2a-4f57-9342-9bce09d91d53,SCRUM,6,True,2025-01-11

In [6]:
# 

gemeinsam_df = pd.concat([df,df2], ignore_index=True)

gemeinsam_df

,MitarbeiterID,Dienstnummer,Vorname,Nachname,Geburtsdatum,Geschlecht,Adresse,Telefon,Email,Familienstand,Beruf,Abteilung,Gehalt_m,Vertrag,Letzte Gehaltsverhandlung,Steuerklasse,Fortbildung,Dauer_d,Abschluss,Durchgeführt_am
0,6fa3cad1-a901-46fc-9b2e-44e170102f0f,HN6431264,Heinfried,Höfig,1967-02-05,divers,"Bärerplatz 46-37, 10264 Lemgo",+49(0)6651 91139,guenther55@example.org,ledig,Altenpfleger,Marketing,101902.0,befristet,2025-01-04,V,NaN,NaN,NaN,NaN
1,54241c49-5d57-4260-8b9a-b39bd82e3596,QX3370028,Sigmar,Thies,1990-02-26,männlich,"Möchlichenstr. 9-2, 57857 Stendal",0961256094,auch-schlauchinadina@example.net,verheiratet,Winzer,Marketing,109952.0,azubi,2023-11-24,I,NaN,NaN,NaN,NaN
2,1cc23984-d455-4089-a7ce-9c073e8fd4a6,YO9477396,Reiner,Ehlert,1986-03-26,weiblich,"Melita-Otto-Weg 4-9, 16909 Güstrow",05238 36756,lindaurenato@example.net,verwitwet,Ausbaufacharbeiter,Einkauf,112739.0,azubi,2025-01-21,V,NaN,NaN,NaN,NaN
3,81dacbc0-6156-4114-9b94-4d6a39102368,CU6669641,Mustafa,Löwer,1967-07-06,männlich,"Boucseinstr. 12, 44938 Riesa",+49(0)3668 79991,hofmannpawel@example.net,ledig,Arzt,HR,51716.0,befristet,2020-09-06,V,NaN,NaN,NaN,NaN
4,28a0a5f2-3a12-44b7-b392-5faabc5453f7,HU4719971,Dajana,Briemer,1993-11-28,weiblich,"Ritterstraße 99, 81748 Mellrichstadt",+49 (0) 2003 128137,katysegebahn@example.org,verheiratet,Altenpfleger,Einkauf,88858.0,azubi,2020-12-05,VI,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
35995,2a8028bb-9722-4e32-a598-706011777e45,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Python Fortgeschritten,2.0,True,2025-07-09
35996,9625c1ba-94b6-4100-98d0-e37a425baec4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Java,7.0,True,2025-07-08
35997,550eed12-7425-46b4-a13d-5fc1791e08d4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Python Fortgeschritten,3.0,True,2025-04-27
35998,1b40b45f-b870-4510-8458-1988fedcc544,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Datenschutz,1.0,True,2025-01-19
35999,fdaef3b1-4f2a-4f57-9342-9bce09d91d53,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,SCRUM,6.0,True,2025-01-11

In [7]:
# Zusammengeführte Tabelle: Mitarbeiter + Fortbildung

_df = df.set_index("MitarbeiterID")
_df2 = df2.set_index("MitarbeiterID")
gemeinsam_df = pd.concat([_df,_df2], axis=1) 

gemeinsam_df

,Dienstnummer,Vorname,Nachname,Geburtsdatum,Geschlecht,Adresse,Telefon,Email,Familienstand,Beruf,Abteilung,Gehalt_m,Vertrag,Letzte Gehaltsverhandlung,Steuerklasse,Fortbildung,Dauer_d,Abschluss,Durchgeführt_am
MitarbeiterID,,,,,,,,,,,,,,,,,,,
6fa3cad1-a901-46fc-9b2e-44e170102f0f,HN6431264,Heinfried,Höfig,1967-02-05,divers,"Bärerplatz 46-37, 10264 Lemgo",+49(0)6651 91139,guenther55@example.org,ledig,Altenpfleger,Marketing,101902,befristet,2025-01-04,V,NaN,NaN,NaN,NaN
54241c49-5d57-4260-8b9a-b39bd82e3596,QX3370028,Sigmar,Thies,1990-02-26,männlich,"Möchlichenstr. 9-2, 57857 Stendal",0961256094,auch-schlauchinadina@example.net,verheiratet,Winzer,Marketing,109952,azubi,2023-11-24,I,NaN,NaN,NaN,NaN
1cc23984-d455-4089-a7ce-9c073e8fd4a6,YO9477396,Reiner,Ehlert,1986-03-26,weiblich,"Melita-Otto-Weg 4-9, 16909 Güstrow",05238 36756,lindaurenato@example.net,verwitwet,Ausbaufacharbeiter,Einkauf,112739,azubi,2025-01-21,V,Python Fortgeschritten,6.0,False,2025-03-23
81dacbc0-6156-4114-9b94-4d6a39102368,CU6669641,Mustafa,Löwer,1967-07-06,männlich,"Boucseinstr. 12, 44938 Riesa",+49(0)3668 79991,hofmannpawel@example.net,ledig,Arzt,HR,51716,befristet,2020-09-06,V,NaN,NaN,NaN,NaN
28a0a5f2-3a12-44b7-b392-5faabc5453f7,HU4719971,Dajana,Briemer,1993-11-28,weiblich,"Ritterstraße 99, 81748 Mellrichstadt",+49 (0) 2003 128137,katysegebahn@example.org,verheiratet,Altenpfleger,Einkauf,88858,azubi,2020-12-05,VI,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8965bba0-771f-478e-b293-a9dc3c800ade,AJ6556586,Jens,Schäfer,1969-08-28,weiblich,"Daniel-Kostolzin-Platz 50-14, 09942 Neustrelitz",+49(0) 475035338,faruk08@example.com,verheiratet,Chemikant,Marketing,94841,azubi,2021-01-14,IV,NaN,NaN,NaN,NaN
4aad8e5f-cdd8-42c9-9af7-78dbc0a8833d,VI9616035,Toralf,Lorch,1983-02-27,divers,"Rennerweg 2/8, 41080 Ochsenfurt",+49(0)4398049014,abraham93@example.com,ledig,Koreanistiker,HR,91256,unbefristet,2023-09-06,VI,NaN,NaN,NaN,NaN
2730fe78-0928-438c-8775-842654b5a6c7,JO0738555,Frauke,Förster,1990-12-27,männlich,"Gaetano-Gehringer-Ring 9, 80545 Meiningen",0552619801,stefani51@example.net,verheiratet,Augenoptiker,HR,94344,azubi,2024-12-24,V,NaN,NaN,NaN,NaN
1a89ea28-c929-4162-9521-18bfdfd127f2,FN3098795,Wolfhard,Cichorius,1959-09-13,divers,"Olivia-Albers-Gasse 8/3, 32760 Merseburg",+49(0)3738934553,hinrich80@example.org,ledig,Beamter,Vertrieb,119096,befristet,2024-05-10,III,NaN,NaN,NaN,NaN
7724d58f-844d-47bd-90ff-bc5cb1bec1a7,CO8155149,Stefanie,Reuter,2006-06-08,divers,"Nelly-Schweitzer-Gasse 27/79, 55073 Gunzenhausen",+49 (0) 7615 593748,donald39@example.net,geschieden,Augenoptiker,HR,98558,befristet,2022-01-07,V,NaN,NaN,NaN,NaN

In [8]:
# Schnittmenge: Mitarbeiter mit Fortbildung

df[df["MitarbeiterID"].isin(df2["MitarbeiterID"])][["Vorname","Nachname"]]


# Differenzmenge: Mitarbeiter ohne Fortbildung
df[~df["MitarbeiterID"].isin(df2["MitarbeiterID"])][["Vorname","Nachname"]]

         Vorname   Nachname
0      Heinfried      Höfig
1         Sigmar      Thies
3        Mustafa      Löwer
4         Dajana    Briemer
5          Theda       Seip
...          ...        ...
29995       Jens    Schäfer
29996     Toralf      Lorch
29997     Frauke    Förster
29998   Wolfhard  Cichorius
29999   Stefanie     Reuter

[24000 rows x 2 columns]

In [9]:
# inner join = Schnittmenge. Nur einträge die in beiden DFs vorkommen, wenn wir über 
# MitarbeiterID-Spalte mergen(verschmelzen)

pd.merge(df,df2, on="MitarbeiterID", how="inner")

,MitarbeiterID,Dienstnummer,Vorname,Nachname,Geburtsdatum,Geschlecht,Adresse,Telefon,Email,Familienstand,Beruf,Abteilung,Gehalt_m,Vertrag,Letzte Gehaltsverhandlung,Steuerklasse,Fortbildung,Dauer_d,Abschluss,Durchgeführt_am
0,1cc23984-d455-4089-a7ce-9c073e8fd4a6,YO9477396,Reiner,Ehlert,1986-03-26,weiblich,"Melita-Otto-Weg 4-9, 16909 Güstrow",05238 36756,lindaurenato@example.net,verwitwet,Ausbaufacharbeiter,Einkauf,112739,azubi,2025-01-21,V,Python Fortgeschritten,6,False,2025-03-23
1,baa0d629-6835-4008-a735-566ca9e1c9f5,JL1550223,Lukas,Stroh,1975-05-15,männlich,"Krausegasse 5-5, 08005 Starnberg",+49(0) 284142065,stolzenikolai@example.org,geschieden,Friseur,IT,96816,unbefristet,2024-03-25,VI,Leadership,1,True,2025-03-08
2,f2b47e90-0d10-471b-bb4b-011215736273,MY8835308,Luise,Zorbach,2000-04-24,divers,"Mohauptweg 6853, 56983 Geithain",+49(0)8999 467078,nbonbach@example.net,geschieden,Arzt,HR,49115,unbefristet,2025-05-07,II,SCRUM,3,False,2025-04-15
3,794c5a64-2b24-48b0-9d81-ecea9741d7ae,JD7439541,Hugo,Mülichen,1971-04-04,weiblich,"Gilbert-Karge-Weg 5-5, 76838 Wertingen",09674 05266,tillmanngotthard@example.org,verheiratet,Designer,Marketing,48797,unbefristet,2022-10-09,IV,SCRUM,2,False,2025-02-05
4,c6a85a04-aaf1-454e-aca8-bbea41da28ff,EM3296984,Giuseppina,Wernecke,1986-03-17,weiblich,"Alois-Pohl-Weg 50, 88382 Chemnitz",+49(0)1528175018,wilhelminelorch@example.net,ledig,Beamter,Einkauf,86260,unbefristet,2021-06-11,IV,SCRUM,6,True,2025-07-10
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5995,de2f9663-7a19-4e6f-9bad-60c28c86ddd8,WU9033556,Francisco,Ladeck,1971-09-15,weiblich,"Schmidtkestraße 4, 64084 Anklam",07473 667426,sagergiorgio@example.org,verwitwet,Arzt,Marketing,97397,befristet,2021-01-04,I,SCRUM,7,False,2025-07-10
5996,3565592a-6e36-4c4a-ad12-182e61d22d1c,PG7613101,Britt,Bloch,1963-11-21,weiblich,"Barkholzring 2, 75401 Witzenhausen",+49(0)3138 14600,artur56@example.org,ledig,Forstwirt,Einkauf,74599,azubi,2025-02-10,IV,Leadership,7,False,2025-05-23
5997,b3710f90-c4c6-43ba-a60b-71be6f07c966,LW1753280,Nikolas,Kambs,1976-04-04,divers,"Heinzgasse 413, 55904 Diepholz",+49(0)3667 035988,stavros34@example.org,verheiratet,Pfleger,Marketing,74510,befristet,2025-01-20,VI,ISO9001,4,True,2025-07-22
5998,bcfafe17-9c7c-432f-8c11-98543a4499fc,EB5108733,Dragica,Mans,1984-03-13,männlich,"August-Trupp-Straße 7, 93622 Kaiserslautern",(09453) 67299,reuterfaruk@example.org,verheiratet,Friseur,Vertrieb,34482,azubi,2022-03-07,VI,Leadership,3,False,2025-05-29
5999,2177b38f-7212-4055-ad1b-f2a444309f9c,CY1700481,Zenta,Albers,1954-12-01,männlich,"Heuserstr. 7636, 19441 Rathenow",+49 (0) 4683 360504,ekremroehricht@example.com,verwitwet,Augenoptiker,HR,42360,unbefristet,2021-07-02,III,Datenschutz,1,False,2025-04-01

In [10]:
# left join = Verschmelzung aber alle zeilen aus linken DF bleiben erhalten.

pd.merge(df,df2, on="MitarbeiterID", how="left")

,MitarbeiterID,Dienstnummer,Vorname,Nachname,Geburtsdatum,Geschlecht,Adresse,Telefon,Email,Familienstand,Beruf,Abteilung,Gehalt_m,Vertrag,Letzte Gehaltsverhandlung,Steuerklasse,Fortbildung,Dauer_d,Abschluss,Durchgeführt_am
0,6fa3cad1-a901-46fc-9b2e-44e170102f0f,HN6431264,Heinfried,Höfig,1967-02-05,divers,"Bärerplatz 46-37, 10264 Lemgo",+49(0)6651 91139,guenther55@example.org,ledig,Altenpfleger,Marketing,101902,befristet,2025-01-04,V,NaN,NaN,NaN,NaN
1,54241c49-5d57-4260-8b9a-b39bd82e3596,QX3370028,Sigmar,Thies,1990-02-26,männlich,"Möchlichenstr. 9-2, 57857 Stendal",0961256094,auch-schlauchinadina@example.net,verheiratet,Winzer,Marketing,109952,azubi,2023-11-24,I,NaN,NaN,NaN,NaN
2,1cc23984-d455-4089-a7ce-9c073e8fd4a6,YO9477396,Reiner,Ehlert,1986-03-26,weiblich,"Melita-Otto-Weg 4-9, 16909 Güstrow",05238 36756,lindaurenato@example.net,verwitwet,Ausbaufacharbeiter,Einkauf,112739,azubi,2025-01-21,V,Python Fortgeschritten,6.0,False,2025-03-23
3,81dacbc0-6156-4114-9b94-4d6a39102368,CU6669641,Mustafa,Löwer,1967-07-06,männlich,"Boucseinstr. 12, 44938 Riesa",+49(0)3668 79991,hofmannpawel@example.net,ledig,Arzt,HR,51716,befristet,2020-09-06,V,NaN,NaN,NaN,NaN
4,28a0a5f2-3a12-44b7-b392-5faabc5453f7,HU4719971,Dajana,Briemer,1993-11-28,weiblich,"Ritterstraße 99, 81748 Mellrichstadt",+49 (0) 2003 128137,katysegebahn@example.org,verheiratet,Altenpfleger,Einkauf,88858,azubi,2020-12-05,VI,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
29995,8965bba0-771f-478e-b293-a9dc3c800ade,AJ6556586,Jens,Schäfer,1969-08-28,weiblich,"Daniel-Kostolzin-Platz 50-14, 09942 Neustrelitz",+49(0) 475035338,faruk08@example.com,verheiratet,Chemikant,Marketing,94841,azubi,2021-01-14,IV,NaN,NaN,NaN,NaN
29996,4aad8e5f-cdd8-42c9-9af7-78dbc0a8833d,VI9616035,Toralf,Lorch,1983-02-27,divers,"Rennerweg 2/8, 41080 Ochsenfurt",+49(0)4398049014,abraham93@example.com,ledig,Koreanistiker,HR,91256,unbefristet,2023-09-06,VI,NaN,NaN,NaN,NaN
29997,2730fe78-0928-438c-8775-842654b5a6c7,JO0738555,Frauke,Förster,1990-12-27,männlich,"Gaetano-Gehringer-Ring 9, 80545 Meiningen",0552619801,stefani51@example.net,verheiratet,Augenoptiker,HR,94344,azubi,2024-12-24,V,NaN,NaN,NaN,NaN
29998,1a89ea28-c929-4162-9521-18bfdfd127f2,FN3098795,Wolfhard,Cichorius,1959-09-13,divers,"Olivia-Albers-Gasse 8/3, 32760 Merseburg",+49(0)3738934553,hinrich80@example.org,ledig,Beamter,Vertrieb,119096,befristet,2024-05-10,III,NaN,NaN,NaN,NaN
29999,7724d58f-844d-47bd-90ff-bc5cb1bec1a7,CO8155149,Stefanie,Reuter,2006-06-08,divers,"Nelly-Schweitzer-Gasse 27/79, 55073 Gunzenhausen",+49 (0) 7615 593748,donald39@example.net,geschieden,Augenoptiker,HR,98558,befristet,2022-01-07,V,NaN,NaN,NaN,NaN

In [11]:
# Outer Join 
# Es werden alle Mitarbeiter aus beiden DFs zusammengeführt -
# egal, ob sie nur in einer, in beiden oder in keiner Tabelle stehen.
# indicator = True erzeugt eine neue Spalte _merge, die folgendes zeigt:
# 1. "left_only": nur in df
# 2. "right_only": nur in df2
# 3. "both": in beiden
outerjoin = pd.merge(df,df2, on="MitarbeiterID", how="outer", indicator=True)
outerjoin

,MitarbeiterID,Dienstnummer,Vorname,Nachname,Geburtsdatum,Geschlecht,Adresse,Telefon,Email,Familienstand,...,Abteilung,Gehalt_m,Vertrag,Letzte Gehaltsverhandlung,Steuerklasse,Fortbildung,Dauer_d,Abschluss,Durchgeführt_am,_merge
0,000033c0-33e2-409f-98f6-3e63496eff71,WD5446949,Carlos,Hölzenbecher,1979-09-05,weiblich,"Ditschlerinring 36/64, 75631 Erbisdorf",03304688943,luebssieglinde@example.net,geschieden,...,Marketing,29841,unbefristet,2025-07-13,IV,NaN,NaN,NaN,NaN,left_only
1,00032f61-5b8a-4e6a-838f-396b69f93b54,HX5891163,Heinz-Jürgen,Neuschäfer,1966-09-13,divers,"Bonbachallee 701, 72046 Plauen",+49 (0) 4385 647343,heinz-ottohaering@example.net,verwitwet,...,Marketing,109088,befristet,2022-06-28,I,NaN,NaN,NaN,NaN,left_only
2,0005b688-9b7c-4003-aedd-8efe1f9b348d,XR2961354,Philomena,Mielcarek,1965-05-19,divers,"Fredi-Thies-Straße 211, 48999 Hoyerswerda",06741006269,uadler@example.org,ledig,...,Marketing,32567,befristet,2025-01-04,II,NaN,NaN,NaN,NaN,left_only
3,000f2c6b-2635-4fc5-bb87-8a89d48c1899,IS1132746,Margita,Pölitz,2004-11-30,männlich,"Else-Wieloch-Weg 9-6, 00567 Ludwigsburg",0522207757,loewerfrederike@example.org,geschieden,...,IT,46625,unbefristet,2022-07-08,II,NaN,NaN,NaN,NaN,left_only
4,00130503-2465-4910-add1-2f669810f694,EU7060171,Erdogan,Holsten,1965-04-22,weiblich,"Immo-Buchholz-Weg 1/5, 46347 Gotha",+49(0)3756 12451,wmisicher@example.org,verheiratet,...,IT,79544,befristet,2023-02-25,I,NaN,NaN,NaN,NaN,left_only
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
29995,fffa7a46-49e8-49e7-9ad8-469b6845d86b,FH9663701,Zoran,Anders,1986-08-01,weiblich,"Schenkstraße 5318, 49360 Suhl",+49(0)6058 359526,annekemargraf@example.net,verwitwet,...,HR,58784,befristet,2021-08-04,V,Python Fortgeschritten,2.0,False,2025-06-18,both
29996,fffc6c2c-3ceb-40a2-8207-88f1dadafc7b,KG2277097,Vinzenz,Schomber,1996-10-17,weiblich,"Beyerplatz 5/7, 57494 Eisleben",04561590811,carinbien@example.org,ledig,...,Einkauf,108855,befristet,2020-10-18,VI,ISO9001,4.0,True,2025-03-24,both
29997,fffe2b1e-653d-4aef-b142-d85d91cd0a59,JQ7762717,Alexa,Röhrdanz,1986-10-28,männlich,"Giuseppe-Harloff-Allee 1/7, 07370 Wolgast",08229 47399,dorothea43@example.net,geschieden,...,IT,117498,unbefristet,2024-05-02,III,Leadership,1.0,True,2025-01-08,both
29998,fffefc44-2c47-4e41-a3de-98270667dd87,IG7198541,Sybilla,Trapp,1951-08-15,weiblich,"Klemtplatz 1, 90247 Aachen",+49(0) 799832960,kobeltphilipp@example.org,verheiratet,...,HR,49113,unbefristet,2022-07-17,VI,NaN,NaN,NaN,NaN,left_only
29999,ffff5abf-3693-478d-8570-8b943ee0eee4,LA8098886,Susann,Wilmsen,1951-12-04,männlich,"Ron-Pohl-Platz 17-36, 85328 Osterode am Harz",+49(0)4436878291,marianna38@example.com,verheiratet,...,IT,40716,befristet,2022-04-07,IV,Python Fortgeschritten,6.0,True,2025-06-22,both

In [12]:
# Übung
# df ist unser Personal-DataFrame
# Erstellen Sie ein sinnvolles zweites DataFrame 
# mit Mitarbeiterinnen, welche in Elternzeit sind
# Zusätzlich erstellen Sie eine Spalte in df mit restlichen
#  Urlaubstagen  
# Erhöhen Sie die Urlaubstage der IT-Abteilung um 2
# Erstellen Sie ein gemeinsames DataFrame, welches Informationen 
# liefert, ob die Mitarbeiter:innen in Elternzeit sind

df["Urlaubstage"] = df["MitarbeiterID"].apply(lambda x: random.randint(0,30))
print(df.loc[df["Abteilung"]=="IT","Urlaubstage"].head(1))
df.loc[df["Abteilung"]=="IT","Urlaubstage"]+=2 
print(df.loc[df["Abteilung"]=="IT","Urlaubstage"].head(1))
df_w = df[df["Geschlecht"]=="weiblich"]
elternzeit_ids = df_w["MitarbeiterID"].sample(1000, random_state = 1) 
# 1000 Mitarbeiterinnen in Elternzeit

elternzeit_list = []

for p in elternzeit_ids:
    eintrag = {
        "MitarbeiterID": p,
        "Beginn": fake.date_between(start_date="-1y", end_date="today"),
        "Ende": fake.date_between(start_date="today", end_date="+1y"),
        "Mutterschutzleistung": random.randint(1200,4000),
    }
    elternzeit_list.append(eintrag)

df3 = pd.DataFrame(elternzeit_list)
df3


outerjoin = pd.merge(df_w, df3, on="MitarbeiterID", how="outer", indicator=True)
outerjoin

6    2
Name: Urlaubstage, dtype: int64
6    4
Name: Urlaubstage, dtype: int64

,MitarbeiterID,Dienstnummer,Vorname,Nachname,Geburtsdatum,Geschlecht,Adresse,Telefon,Email,Familienstand,...,Abteilung,Gehalt_m,Vertrag,Letzte Gehaltsverhandlung,Steuerklasse,Urlaubstage,Beginn,Ende,Mutterschutzleistung,_merge
0,000033c0-33e2-409f-98f6-3e63496eff71,WD5446949,Carlos,Hölzenbecher,1979-09-05,weiblich,"Ditschlerinring 36/64, 75631 Erbisdorf",03304688943,luebssieglinde@example.net,geschieden,...,Marketing,29841,unbefristet,2025-07-13,IV,7,NaN,NaN,NaN,left_only
1,00130503-2465-4910-add1-2f669810f694,EU7060171,Erdogan,Holsten,1965-04-22,weiblich,"Immo-Buchholz-Weg 1/5, 46347 Gotha",+49(0)3756 12451,wmisicher@example.org,verheiratet,...,IT,79544,befristet,2023-02-25,I,25,NaN,NaN,NaN,left_only
2,001a40b5-d4a3-4bf5-85ca-6bb26c1e8ca7,RM3548203,Mechthild,Mielcarek,1988-03-21,weiblich,"Erik-Boucsein-Gasse 38, 07274 Eggenfelden",00365 917851,lotti14@example.org,verwitwet,...,Marketing,97948,azubi,2021-02-24,V,18,NaN,NaN,NaN,left_only
3,001b7466-2376-48ed-a7ef-4e25d31df85e,DI0288036,Hans-Willi,Hoffmann,1980-03-11,weiblich,"Heinrichweg 785, 32532 Stuttgart",+49(0) 506085463,van-der-dussenole@example.net,verheiratet,...,Marketing,70046,azubi,2025-07-08,VI,20,NaN,NaN,NaN,left_only
4,001bcb06-80fe-42b9-a6ab-4f0909407a52,IL8934225,Fredy,Kruschwitz,1997-04-05,weiblich,"Joachim-Otto-Ring 18/88, 07565 Feuchtwangen",+49(0)9623941304,henryk65@example.net,verheiratet,...,Vertrieb,112234,unbefristet,2021-07-03,IV,15,NaN,NaN,NaN,left_only
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9985,ffe70eeb-dd2a-47b1-ad5c-677323df1cbf,ET4316697,Danilo,Girschner,1981-09-30,weiblich,"van der Dussenring 3-2, 14102 Mayen",+49(0)5754 09488,alicjaditschlerin@example.net,verwitwet,...,IT,83622,befristet,2022-06-05,IV,29,NaN,NaN,NaN,left_only
9986,ffe7ab8c-00b7-43f1-9956-88f144f706cb,KT7907383,Änne,Jockel,1967-04-16,weiblich,"Dörschnerallee 72-24, 58748 Wittstock",+49(0)5173 39456,rohlederurs@example.com,ledig,...,Vertrieb,101132,azubi,2023-02-07,IV,24,NaN,NaN,NaN,left_only
9987,fffa7a46-49e8-49e7-9ad8-469b6845d86b,FH9663701,Zoran,Anders,1986-08-01,weiblich,"Schenkstraße 5318, 49360 Suhl",+49(0)6058 359526,annekemargraf@example.net,verwitwet,...,HR,58784,befristet,2021-08-04,V,14,NaN,NaN,NaN,left_only
9988,fffc6c2c-3ceb-40a2-8207-88f1dadafc7b,KG2277097,Vinzenz,Schomber,1996-10-17,weiblich,"Beyerplatz 5/7, 57494 Eisleben",04561590811,carinbien@example.org,ledig,...,Einkauf,108855,befristet,2020-10-18,VI,27,NaN,NaN,NaN,left_only
9989,fffefc44-2c47-4e41-a3de-98270667dd87,IG7198541,Sybilla,Trapp,1951-08-15,weiblich,"Klemtplatz 1, 90247 Aachen",+49(0) 799832960,kobeltphilipp@example.org,verheiratet,...,HR,49113,unbefristet,2022-07-17,VI,30,NaN,NaN,NaN,left_only

# String-Methoden in pandas

In [13]:
df["Beruf"].str.lower()
df["Beruf"].str.upper() 
df["Adresse"].str.title() # Anfangsbuchstabe jedes Wortes groß
df["Adresse"].str.capitalize() # Anfangsbuchstabe vom String

0                           Bärerplatz 46-37, 10264 lemgo
1                       Möchlichenstr. 9-2, 57857 stendal
2                      Melita-otto-weg 4-9, 16909 güstrow
3                            Boucseinstr. 12, 44938 riesa
4                    Ritterstraße 99, 81748 mellrichstadt
                               ...
29995     Daniel-kostolzin-platz 50-14, 09942 neustrelitz
29996                     Rennerweg 2/8, 41080 ochsenfurt
29997           Gaetano-gehringer-ring 9, 80545 meiningen
29998            Olivia-albers-gasse 8/3, 32760 merseburg
29999    Nelly-schweitzer-gasse 27/79, 55073 gunzenhausen
Name: Adresse, Length: 30000, dtype: object

In [14]:
df["Beruf"].str.replace("er","er:in") # alle Vorkommnisse von "er" durch "er:in" ersetzen

0              Altenpfleger:in
1                    Winzer:in
2        Ausbaufacharbeiter:in
3                         Arzt
4              Altenpfleger:in
                 ...
29995                Chemikant
29996         Koreanistiker:in
29997          Augenoptiker:in
29998               Beamter:in
29999          Augenoptiker:in
Name: Beruf, Length: 30000, dtype: object

In [15]:
df["Email"].str.len()
df["Email"].str.endswith(".de")
df["Abteilung"].str.find("I") # gibt die erste vorkommende Position sonst -1
df["Urlaubstage"]=df["Urlaubstage"].astype(str)
df["Urlaubstage"].str.zfill(2)

# Zählen Sie, wie viele Emailadressen mit example.com enden
# 1. Möglichkeit
df["Email"].str.endswith("example.com").sum()

# 2. Möglichkeit

len(df["Email"][df["Email"].str.endswith("example.com")])

# oder 
df["Email"][df["Email"].str.endswith("example.com")].count()

np.int64(10104)

In [16]:
# Erstellen Sie eine Spalte mit Initialien 
# z.b. Marc Schmidt -> MS
df["Initialien"] = df["Vorname"].str.get(0) + df["Nachname"].str.get(0)
df["Initialien"] = df["Vorname"].str[0] + df["Nachname"].str[0]
df["Initialien"]

0        HH
1        ST
2        RE
3        ML
4        DB
         ..
29995    JS
29996    TL
29997    FF
29998    WC
29999    SR
Name: Initialien, Length: 30000, dtype: object

In [17]:
df["Nachname"].str.contains("er",case=True).sum()

np.int64(9467)

In [18]:
df["Email"].str.contains(r"@\w+\.", regex=True)

0        True
1        True
2        True
3        True
4        True
         ...
29995    True
29996    True
29997    True
29998    True
29999    True
Name: Email, Length: 30000, dtype: bool

In [19]:
%pip install openpyxl # fürs excel

Requirement already satisfied: openpyxl in /Users/grigo/gits/seminars/gfu/Python_individuell/.venv/lib/python3.12/site-packages (3.1.5)
Requirement already satisfied: et-xmlfile in /Users/grigo/gits/seminars/gfu/Python_individuell/.venv/lib/python3.12/site-packages (from openpyxl) (2.0.0)
Note: you may need to restart the kernel to use updated packages.

In [20]:
df.to_csv("personal_export.csv", index=False,sep=",")
df.to_csv("personal_export_semikolon.csv", index=False,sep=";")
df.to_excel("personal_export.xlsx", index=False, sheet_name="Tabelle1")
# df.to_parquet("personal_export.parquet")

In [21]:
# columns ... JSON aus Spalten
# records ... Zeilen als JSON
# split ... "columns": ..., "index": ... , "data":... 
# values ... Liste der Zeilen
# table ... JSON mit Schema
df.to_json("personal_export.json", orient='table', lines=False)

In [22]:
import sqlite3

with sqlite3.connect("personal.db") as con:
    df.to_sql("personal", con, if_exists="replace", index=False)

In [23]:
%pip install tabulate

Requirement already satisfied: tabulate in /Users/grigo/gits/seminars/gfu/Python_individuell/.venv/lib/python3.12/site-packages (0.9.0)
Note: you may need to restart the kernel to use updated packages.

In [25]:
from tabulate import tabulate

with open("out.txt", "w") as f:
    f.write(tabulate(df, tablefmt= "plain", showindex=False))

In [ ]:
pd.read_xml